Gruntfile.js, package.json, yarn.lock
Makes the deployment smaller.
- removes the source-map from the final build
- use uglifyjs to minimize the file. This cuts down the total size from 8MB to 4MB.
=> Miminize javascript before deployment

public/js/components/app.js, public/js/components/feature_table.js, public/js/components/layer_details.js, public/js/components/map.js, public/js/components/table_of_contents.js, public/style/main.css
@thomasneirynck 
Here are the few things I did:
- Altered layer details to user a header and paragraph and moved the reporting section to below the table (since it doesn’t change per layer).
- Somewhat fixed some mobile layout stuff (a few things still need to be permanently fixed in EUI)
- Reduced text size of the tooltip content
Since there is only one action per row (show on map) I would highly suggest moving this to an `onClick` event on the row itself. That will give more room for the actual table contents. It also may be a nice feature to auto-scroll back up to the map when they click a row in case their window is short and the map isn't in view.
=> Little design tweaks

public/config.json
Fixes #36
The staging manifest can be loaded by adding the `?manifest=staging` query string to the URL.
=> Use production manifest as default

public/config.json
With the recent change to ems-file-service, we've updated the URL for the staging manifest. The old URL should not be used anymore.
Once merged, you should be able to see the correct files in staging from http://maps.elastic.co/?manifest=staging#file/USA%20States.
=> Update staging URL for EMS

public/config.json, public/js/components/app.js, public/js/components/feature_table.js, public/js/components/layer_details.js, public/js/components/map.js, public/js/components/table_of_contents.js, public/js/ems_client.js, public/js/file_layer.js, public/js/modify_url.js, public/js/origin.js, public/js/tms_service.js, public/main.js
This updates the EMS Landing Page to work with the EMS v6.6 file manifest.
There are a few features in EMS v6.6 that this does not handle yet. 
After this is merged, Kibana should be updated to point to the v6.6 release of EMS Landing Page.
=> Update to work with EMS v6.6

package.json, public/js/components/map.js, yarn.lock
Cherry-picks the following commit to v6.6:
* [v2] Add basemap attribution #64
=> [v6.6] Add basemap attribution

package.json, public/js/components/app.js, yarn.lock
Cherry-picks the following commit to v6.6:
* Use react-https-redirect to redirect to https #67
=> [v6.6] Use react-https-redirect to redirect to https

package.json, public/js/components/app.js, yarn.lock
This uses the[ react-https-redirect ](https://github.com/mbasso/react-https-redirect) library to redirect http to https. This also has the benefit of not redirecting when using `http://localhost:<port>` in development. To test https redirection in development, use `http://0.0.0.0:<port>`.
Fixes #18
=> [v2] Use react-https-redirect to redirect to https

public/config.json
New layers will be changing for 7.0 release so we should use the correct manifests.
=> Update 7.0 version to use EMS 7.0 manifests

public/main.js
This implements a safer check for locale inputs as well as merging the deployment input check from v6.6.
This should get merged into v7.0.
Replaces #84.
=> [v6.7] Safe locale check

deployProduction.sh, package.json, public/config.json, public/js/manifest_parser_v2.js, webpack.common.js, yarn.lock
Forward porting #93 into v6.6.
Fixes #91. This PR adds support for higher zoom levels on https://maps.elastic.co via a configurable Elastic Maps Service license key.
=> [v6.6] Enable higher zoom levels

.ci/jobs/elastic+ems-landing-page+v7.4+stage.yml
This creates the CI for the 7.4 branch of the ems landing page. We will expect this release to  support vector tile basemaps.
=> Create 7.4 branch job

public/config.json
New layers in the `feature-layers` branch of the ems-file-service can
be tested by adding `?manifest=testing` to the URL.
=> Add testing manifest for new layers

public/config.json
- Add testing manifest for new layers (#117)
=> [v7.2] Add testing manifest for new layers (#117)

public/config.json
- testing url should be https (#119)
=> [v7.2] testing url should be https (#119)

public/config.json, public/main.js
Fixes #91. This adds a configurable license to enable zoom levels greater than 10 for basemaps.
This should be backported to 7.4.
=> Enable higher zoom levels

public/js/components/app.js
While fixing a merge conflict in backport #133 I inadvertently introduced a bug in the v2 branch. This reverts the errant lines from the backport.
=> Revert change caused by merge conflict in #133

.ci/jobs/defaults.yml
Now that 7.4 is released, let's update https://maps.elastic.co to the v7.4 branch which has vector tiles.
=> Update https://maps.elastic.co to the v7.4 branch

package.json, yarn.lock
Should be backported only to v7.4.
I tested this with a virtual machine running IE11.
=> Fix IE11 compatibility

package.json, yarn.lock
- Bump @elastic/ems-client to latest patch (#151)
=> [v7.4] Bump @elastic/ems-client to latest patch (#151)

package.json, public/js/components/map.js, yarn.lock
Support for RTL languages (such as Arabic and Hebrew) [was added to Kibana in v7.6.0](https://github.com/elastic/kibana/pull/54842). We should also add support in the v7.6 release here. 
For example, note the respective Arabic and Hebrew labels for [Cairo](https://en.wikipedia.org/wiki/Cairo) and [Tel Aviv](https://en.wikipedia.org/wiki/Tel_Aviv) in the screenshots below.
Before:
After:
=> Add support for RTL languages

webpack.common.js
ems-client has a dependency on node-fetch which is only used for Node.js. Webpack throws a warning when it sees the iconv-loader.js file in the encoding dependency of node-fetch. We only use the browser target of ems-client so node-fetch is not used here. So we can avoid this warning by telling webpack to ignore the iconv-loader.js file.
=> Fix webpack warning about iconv-loader

.backportrc.json, .ci/jobs/elastic+ems-landing-page+v7.6.yml
This will add v7.6 branch to CI to build the v7.6 version of ems-landing-page. After publishing the v7.6 version will be available at https://maps.elastic.co/v7.6. 
This follows the instructions for adding a new version in the [CONTRIBUTING.md](https://github.com/elastic/ems-landing-page/blob/master/CONTRIBUTING.md#new-releases).
=> Add v7.6 branch to ci

webpack.common.js
- Fix webpack warning about iconv-loader (#155)
=> [v7.4] Fix webpack warning about iconv-loader (#155)

webpack.common.js
- Fix webpack warning about iconv-loader (#155)
=> [v7.6] Fix webpack warning about iconv-loader (#155)

.backportrc.json, .ci/jobs/defaults.yml
This PR will update https://maps.elastic.co to use the v7.6 branch.
=> Default to v7.6

package.json, public/main.js, webpack.common.js, yarn.lock
This will allow us to load the config at runtime rather than compiling `config.json` in the webpack build. A benefit of this is greater flexibility for cases where ems-landing-page is hosted from another location and EMS is only available through a proxy or a different API. 
How to test this PR:
1) `yarn && yard compile`
1) Change the production emsFileApiUrl in `build/release/config.json` to `https://vector-staging.maps.elastic.co`. 
1) Serve the `build/release` directory (ex. `cd build/release && npx http-serve`).
1) Open http://localhost:8080 and check the Network requests to see that the file assets are served from the `https://vector-staging.maps.elastic.co` host.
=> Load config file at runtime

.ci/jobs/elastic+ems-landing-page+v7.7.yml, package.json, public/config.json, public/main.js, yarn.lock
Things to check for:
* Requests for tile and file manifests should be `.../v7.7/manifest`
* `my_app_name=ems-landing-page` in query string requests
* `my_app_version=7.7.0` in query string requests 
First we should merge https://github.com/elastic/ems-client/pull/19, publish @elastic/ems-client@7.7.1, and update the dependency in this PR.
=> Update to EMS v7.7

public/main.js
This bug was not caught earlier because the emsVersion has a default in ems-client.
=> Fix parsing emsVersion from config

public/main.js
- Fix parsing emsVersion from config (#182)
=> [v7.6] Fix parsing emsVersion from config (#182)

package.json, public/js/components/map.js, public/main.js, yarn.lock
- Allow relative API URLs in config (#181)
=> [v7.7] Allow relative API URLs in config (#181)

public/js/components/app.js, yarn.lock
Fixes #88 
When the #file anchor in the URL is empty it should redirect to the first layer ("world_countries"). 
Here are some URLs to test.
- http://localhost:8080/#file compare against https://maps.elastic.co/#file
- http://localhost:8080/#file/ compare against https://maps.elastic.co/#file/
- http://localhost:8080/# compare against https://maps.elastic.co/# (should work in both)
=> Handle empty #file anchor in URL

public/js/components/app.js
=> [v7.7] Handle empty #file anchor in URL (#186)

public/js/components/app.js
=> [v7.6] Handle empty #file anchor in URL (#186)

public/js/components/app.js
=> [v7.4] Handle empty #file anchor in URL (#186)

public/js/components/app.js
=> [v7.2] Handle empty #file anchor in URL (#186)

public/js/components/app.js
=> [v7.0] Handle empty #file anchor in URL (#186)

public/js/components/app.js
=> [v6.7] Handle empty #file anchor in URL (#186)

public/js/components/app.js
=> [v6.6] Handle empty #file anchor in URL (#186)

CONTRIBUTING.md, package.json
😅  
In order to send the correct `my_app_version` query parameter to the API, we need to bump the package.json version.
=> Bump package.json version for 7.8

.ci/jobs/elastic+ems-landing-page+v7.8.yml, CONTRIBUTING.md, package.json, public/config.json, yarn.lock
- Publish 7.8 (#198)
- Bump package.json version for 7.8 (#199)
=> [v7.8] Publish 7.8 (#198) | Bump package.json version for 7.8 (#199)

.ci/jobs/defaults.yml
- Bump https://maps.elastic.co to v7.7 (#202)
=> [v7.7] Bump https://maps.elastic.co to v7.7 (#202)

yarn.lock
=> [v2] Bump websocket-extensions from 0.1.3 to 0.1.4 (#207)

yarn.lock
=> [v6.6] Bump websocket-extensions from 0.1.3 to 0.1.4 (#207)

yarn.lock
=> [v7.0] Bump websocket-extensions from 0.1.3 to 0.1.4 (#207)

yarn.lock
=> [v7.2] Bump websocket-extensions from 0.1.3 to 0.1.4 (#207)

yarn.lock
=> [v7.4] Bump websocket-extensions from 0.1.3 to 0.1.4 (#207)

yarn.lock
=> [v7.6] Bump websocket-extensions from 0.1.3 to 0.1.4 (#207)

yarn.lock
=> [v7.7] Bump websocket-extensions from 0.1.3 to 0.1.4 (#207)

yarn.lock
=> [v7.8] Bump websocket-extensions from 0.1.3 to 0.1.4 (#207)

.ci/jobs/defaults.yml
This bumps the root at https://maps.elastic.co for the v7.8 release per instructions in CONTRIBUTING.md.
=> Bump root to v7.8

README.md, public/index.hbs, webpack.common.js
The http -> https redirect now happens automatically (already deployed) by the Bekitzur service.
=> Remove https redirector - no longer needed

README.md, public/index.hbs, webpack.common.js
- Remove https redirector - no longer needed (#220)
=> [v7.6] Remove https redirector - no longer needed (#220)

README.md, public/index.hbs, webpack.common.js
- Remove https redirector - no longer needed (#220)
=> [v7.7] Remove https redirector - no longer needed (#220)

README.md, public/index.hbs, webpack.common.js
- Remove https redirector - no longer needed (#220)
=> [v7.8] Remove https redirector - no longer needed (#220)

README.md, public/index.hbs, webpack.common.js
- Remove https redirector - no longer needed (#220)
=> [v7.9] Remove https redirector - no longer needed (#220)

public/js/components/layer_details.js
Generate the attribution-string safely client-side. Similar change as https://github.com/elastic/kibana/pull/70888 in Kibana.
=> Generate attribution-string client-side

package.json, yarn.lock
Bumps ems-client to 7.9.4
See https://github.com/elastic/ems-client/pull/46 and https://github.com/elastic/ems-landing-page/pull/228
=> Bump ems-client

.ci/jobs/defaults.yml
Now that 7.9 is released, https://maps.elastic.co should use the v7.9 manifest. 
Per instructions in [CONTRIBUTING.md](https://github.com/elastic/ems-landing-page/blob/master/CONTRIBUTING.md#new-releases).
=> Bump root to v7.9

package.json, public/js/components/app.js, public/js/components/layer_details.js, yarn.lock
- Generate attribution-string safely (#228)
- Add external links (#236)
=> [v7.7] Generate attribution-string safely (#228) | Add external links (#236)

package.json, public/js/components/app.js, public/js/components/layer_details.js, yarn.lock
- Generate attribution-string safely (#228)
- Add external links (#236)
=> [v7.6] Generate attribution-string safely (#228) | Add external links (#236)

webpack.common.js
Currently, EMS landing page always expects assets to be available at the root web server path. It is currently not possible to load assets from a path other than `/`. We can see this by running `yarn build && npx http-server . -o /build/release` from the repo root directory. Note that all assets return 404 because they are expected to be available at `/` instead of relative to the current path. 
This PR introduces a `ASSET_PATH` environment variable that changes the webpack `[output.publicPath](https://webpack.js.org/configuration/output/#outputpublicpath)` variable. We can test this PR by running `ASSET_PATH=/build/release/ yarn build && npx http-server . -o /build/release` from the repo root directory.
Note, it's imperative to include a trailing slash when specifying the `ASSET_PATH`.
=> Build option to host under path other than root

webpack.common.js
#258 sets the wrong default for `[publicPath](https://webpack.js.org/configuration/output/#outputpublicpath)`. 😖 The default should be `''`, not `/`. You can see that the icons have disappeared in https://maps-staging.elastic.co/master. Hopefully this PR fixes that.
=> Use default publicPath if ASSET_PATH is not specified

webpack.common.js
=> [v6.6] Build option to host under path other than root (#258)

webpack.common.js
=> [v6.7] Build option to host under path other than root (#258)

webpack.common.js
=> [v7.0] Build option to host under path other than root (#258)

webpack.common.js
=> [v7.2] Build option to host under path other than root (#258)

webpack.common.js
=> [v7.4] Build option to host under path other than root (#258)

webpack.common.js
=> [v7.6] Build option to host under path other than root (#258)

webpack.common.js
=> [v7.7] Build option to host under path other than root (#258)

webpack.common.js
=> [v7.8] Build option to host under path other than root (#258)

webpack.common.js
=> [v7.9] Build option to host under path other than root (#258)

webpack.common.js
=> [v7.10] Build option to host under path other than root (#258)

webpack.common.js
=> [v7.10] Use default publicPath if ASSET_PATH is not specified (#259)

webpack.common.js
=> [v7.9] Use default publicPath if ASSET_PATH is not specified (#259)

webpack.common.js
=> [v7.8] Use default publicPath if ASSET_PATH is not specified (#259)

webpack.common.js
=> [v7.7] Use default publicPath if ASSET_PATH is not specified (#259)

webpack.common.js
=> [v7.6] Use default publicPath if ASSET_PATH is not specified (#259)

webpack.common.js
=> [v7.4] Use default publicPath if ASSET_PATH is not specified (#259)

webpack.common.js
=> [v7.2] Use default publicPath if ASSET_PATH is not specified (#259)

webpack.common.js
=> [v7.0] Use default publicPath if ASSET_PATH is not specified (#259)

webpack.common.js
=> [v6.7] Use default publicPath if ASSET_PATH is not specified (#259)

webpack.common.js
=> [v6.6] Use default publicPath if ASSET_PATH is not specified (#259)

.ci/jobs/defaults.yml
- Bump root maps.elastic.co to v7.10 (#284)
=> [v7.10] Bump root maps.elastic.co to v7.10 (#284)

package.json, public/js/components/feature_table.js, yarn.lock
Fixes #255 
The "Download <format type>" button tries to get the "geojson" format of the layer. If a "geojson" format is unavailable, the default format type is used.
This requires https://github.com/elastic/ems-client/pull/53.
=> Download GeoJSON when available

public/js/components/app.js, public/js/components/layer_details.js
Fixes #304. This adds a content pane for the currently selected tile layer. 
This also adds the `layer_id` for the currently selected layers in the UI.
=> Add details for currently selected tile layer

.ci/jobs/defaults.yml
This will bump https://maps.elastic.co to 7.12. 
Following the instructions in https://github.com/elastic/ems-landing-page/blob/master/CONTRIBUTING.md#new-releases.
=> Bump https://maps.elastic.co to 7.12

.ci/jobs/defaults.yml
Backports the following commits to v7.12:
- Update defaults.yml (#311)
=> [v7.12]  Bump https://maps.elastic.co to 7.12 (#311)

public/config.json, public/js/components/app.js, public/main.js
Changes the header logo to allow a service name specified in the config file. Defaults to "Elastic Maps Service" when there is no service name specified.
*Note* this also changes the href to link to the root rather than an anchor link. This is useful when this page is hosted under a path such as in Elastic Maps Server.
=> Allow configurable service name in header

package.json, public/js/components/app.js, public/js/components/feature_table.js, public/js/components/layer_details.js, public/main.css, yarn.lock
Fixes #354
Fixes #302
This PR upgrades to the last EUI version and adds some minor visual changes to accommodate better the layer details and the feature table.
This PR should only be merged once we are sure Kibana gets Amsterdam as default theme by backporting this PR elastic/kibana#94370 to the release branch.
=> Bump dns-packet and EUI and switch to Amsterdam theme

.ci/jobs/elastic+ems-landing-page+v7.15.yml
In #361, we forgot to create a CI job to publish the 7.15 branch. 
This adds that CI job.
=> Add CI job for 7.15 branch

yarn.lock
Backports the following commits to v7.15:
- Bump path-parse from 1.0.6 to 1.0.7 (#360)
=> [v7.15] Bump path-parse from 1.0.6 to 1.0.7 (#360)

package.json, yarn.lock
Backports the following commits to v7.15:
- Bump url-parse from 1.5.1 to 1.5.2 (#362)
=> [v7.15] Bump url-parse from 1.5.1 to 1.5.2 (#362)

public/js/components/app.js, public/js/components/table_of_contents.js, webpack.common.js, webpack.dev.js, webpack.prod.js
Fixes #227
Using `appendIconComponentCache` function in EUI we can inline icons so we can safely remove the individual icon bundles generated by webpack with the `cleanAfterEveryBuildPatterns` option from the `CleanWebpackPlugin` (in Webpack 5 this won't be necessary as it's supported directly with the `output.clean` option).
Also, the `FaviconsWebpackPlugin` is configured to skip generating icons for different mobile platforms cleaning the resulting HTML and the `assets` folder.
=> Reduce output assets number

yarn.lock
Backports the following commits to v7.16:
- Bump path-parse from 1.0.6 to 1.0.7 (#360)
=> [v7.16] Bump path-parse from 1.0.6 to 1.0.7 (#360)

package.json, yarn.lock
Backports the following commits to v7.16:
- Bump url-parse from 1.5.1 to 1.5.2 (#362)
=> [v7.16] Bump url-parse from 1.5.1 to 1.5.2 (#362)

package.json, yarn.lock
Backports the following commits to v8.0:
- Bump url-parse from 1.5.1 to 1.5.2 (#362)
=> [v8.0] Bump url-parse from 1.5.1 to 1.5.2 (#362)

package.json, yarn.lock
EMS Landing Page needs to bump `master` to `8.1` stack version.
=> Bump to EMS 8.1.0

package.json
Since it is compatible, and following the same pattern as in [EMS File Service](https://github.com/elastic/ems-file-service/blob/master/package.json#L13), we can allow systems with Node 12 to build the page.
=> Allow to build from node 12

package.json
Backports the following commits to v7.16:
- Allow to build from node 12 (#395)
=> [v7.16] Allow to build from node 12 (#395)

package.json
Backports the following commits to v7.17:
- Allow to build from node 12 (#395)
=> [v7.17] Allow to build from node 12 (#395)

package.json
Backports the following commits to v7.15:
- Allow to build from node 12 (#395)
=> [v7.15] Allow to build from node 12 (#395)

package.json
Backports the following commits to v8.0:
- Allow to build from node 12 (#395)
=> [v8.0] Allow to build from node 12 (#395)

.gitignore, yarn.lock
Replaces #401 #404 #405
- added vscode folder to gitignore
- Bump nanoid from 3.1.30 to 3.2.0
- Bump simple-get from 3.1.0 to 3.1.1
- Bump follow-redirects from 1.14.6 to 1.14.8
=> February updates

package.json, yarn.lock
This is an automatic backport of pull request #425 to v7.17.
=> [v7.17] Bump moment from 2.29.1 to 2.29.2 (#425)

package.json, yarn.lock
This is an automatic backport of pull request #425 to v8.2.
=> [v8.2] Bump moment from 2.29.1 to 2.29.2 (#425)

public/js/components/layer_details.js
Fixes #430
Related to elastic/kibana#130948
Includes a badge for Vector Layers indicating the default format advertised by EMS.
=> Display format for File Layers

.backportrc.json, .ci/jobs/elastic+ems-landing-page+v8.4.yml, package.json
This will backport the following commits from `master` to `v8.4`:
- [Bump to 8.4.0 (#436)](https://github.com/elastic/ems-landing-page/pull/436)
=> [v8.4] Bump to 8.4.0 (#436)

public/js/components/layer_details.js
This will backport the following commits from `master` to `v8.3`:
- [Add a badge with default format for FileLayers (#431)](https://github.com/elastic/ems-landing-page/pull/431)
=> [v8.3] Add a badge with default format for FileLayers (#431)

yarn.lock
This will backport the following commits from `master` to `v8.2`:
- [Bump eventsource from 1.1.0 to 1.1.1 (#441)](https://github.com/elastic/ems-landing-page/pull/441)
=> [v8.2] Bump eventsource from 1.1.0 to 1.1.1 (#441)

public/config.json
Changing to `tiles.elastic.dev` for `manifest=testing`.
This will help to review basemaps refreshes before going to production.
=> Vector tiles from .dev when manifest query param is testing

public/js/components/map.js, public/main.css
Adds a Maplibre fullscreen control changing the default button icon by EUI version for consistency.
The aim of this change is to make exploring the map easier.
=> Include a fullscreen control on the map

public/js/components/app.js
Kibana has used the desaturated basemap as the default for some time now. We should also use the desaturated style as default for landing page.
=> Use desaturated map as the default

public/js/components/app.js
- [Use desaturated map as the default (#458)](https://github.com/elastic/ems-landing-page/pull/458)
=> [v8.6] Use desaturated map as the default (#458)

package.json, public/js/components/app.js, public/js/components/map.js, public/js/components/table_of_contents.js, public/main.css, yarn.lock
- [Update dependencies (#460)](https://github.com/elastic/ems-landing-page/pull/460)
- [Upgrade chroma-js@2.4.2 (#464)](https://github.com/elastic/ems-landing-page/pull/464)
=> [v8.6] Update dependencies (#460) | Upgrade chroma-js@2.4.2 (#464)

yarn.lock
- [Bump minimatch from 3.0.4 to 3.1.2 (#463)](https://github.com/elastic/ems-landing-page/pull/463)
=> [v8.6] Bump minimatch from 3.0.4 to 3.1.2 (#463)

yarn.lock
- [Bump minimatch from 3.0.4 to 3.1.2 (#463)](https://github.com/elastic/ems-landing-page/pull/463)
=> [v8.5] Bump minimatch from 3.0.4 to 3.1.2 (#463)

package.json, yarn.lock
- [Upgrade loader-utils (#470)](https://github.com/elastic/ems-landing-page/pull/470)
=> [v8.5] Upgrade loader-utils (#470)

package.json, yarn.lock
- [Upgrade loader-utils (#470)](https://github.com/elastic/ems-landing-page/pull/470)
=> [v8.6] Upgrade loader-utils (#470)

package.json, yarn.lock
- [Upgrade loader-utils (#470)](https://github.com/elastic/ems-landing-page/pull/470)
=> [v8.7] Upgrade loader-utils (#470)

package.json, yarn.lock
- [fix: upgrade @elastic/eui from 70.1.0 to 70.2.0 (#474)](https://github.com/elastic/ems-landing-page/pull/474)
=> [v8.5] fix: upgrade @elastic/eui from 70.1.0 to 70.2.0 (#474)

package.json, yarn.lock
- [fix: upgrade @elastic/eui from 70.2.1 to 70.3.0 (#484)](https://github.com/elastic/ems-landing-page/pull/484)
=> [v8.6] fix: upgrade @elastic/eui from 70.2.1 to 70.3.0 (#484)

package.json, yarn.lock
- [fix: upgrade @elastic/eui from 70.2.1 to 70.3.0 (#484)](https://github.com/elastic/ems-landing-page/pull/484)
=> [v8.5] fix: upgrade @elastic/eui from 70.2.1 to 70.3.0 (#484)

package.json, yarn.lock
- [fix: upgrade @elastic/eui from 70.3.0 to 70.4.0 (#488)](https://github.com/elastic/ems-landing-page/pull/488)
=> [v8.6] fix: upgrade @elastic/eui from 70.3.0 to 70.4.0 (#488)

package.json, yarn.lock
- [fix: upgrade @elastic/eui from 70.3.0 to 70.4.0 (#488)](https://github.com/elastic/ems-landing-page/pull/488)
=> [v8.7] fix: upgrade @elastic/eui from 70.3.0 to 70.4.0 (#488)

package.json, yarn.lock
- [fix: upgrade @elastic/eui from 70.3.0 to 70.4.0 (#488)](https://github.com/elastic/ems-landing-page/pull/488)
=> [v8.5] fix: upgrade @elastic/eui from 70.3.0 to 70.4.0 (#488)

yarn.lock
- [Bump eventsource from 1.1.0 to 1.1.1 (#441)](https://github.com/elastic/ems-landing-page/pull/441)
=> [v7.17] Bump eventsource from 1.1.0 to 1.1.1 (#441)

package.json, yarn.lock
- [Bump moment from 2.29.2 to 2.29.4 (#449)](https://github.com/elastic/ems-landing-page/pull/449)
=> [v7.17] Bump moment from 2.29.2 to 2.29.4 (#449)

package.json, yarn.lock
- [March Updates (#418)](https://github.com/elastic/ems-landing-page/pull/418)
=> [v7.17] March Updates (#418)

yarn.lock
- [Bump minimatch from 3.0.4 to 3.1.2 (#463)](https://github.com/elastic/ems-landing-page/pull/463)
=> [v7.17] Bump minimatch from 3.0.4 to 3.1.2 (#463)

package.json, yarn.lock
- [Upgrade loader-utils (#470)](https://github.com/elastic/ems-landing-page/pull/470)
=> [v7.17] Upgrade loader-utils (#470)

yarn.lock
- [Bump decode-uri-component from 0.2.0 to 0.2.2 (#477)](https://github.com/elastic/ems-landing-page/pull/477)
=> [v7.17] Bump decode-uri-component from 0.2.0 to 0.2.2 (#477)

yarn.lock
- [Bump qs from 6.5.2 to 6.5.3 (#479)](https://github.com/elastic/ems-landing-page/pull/479)
=> [v7.17] Bump qs from 6.5.2 to 6.5.3 (#479)

yarn.lock
- [Bump json5 from 1.0.1 to 1.0.2 (#502)](https://github.com/elastic/ems-landing-page/pull/502)
=> [v8.7] Bump json5 from 1.0.1 to 1.0.2 (#502)

yarn.lock
- [Bump json5 from 1.0.1 to 1.0.2 (#502)](https://github.com/elastic/ems-landing-page/pull/502)
=> [v8.6] Bump json5 from 1.0.1 to 1.0.2 (#502)

yarn.lock
- [Bump json5 from 1.0.1 to 1.0.2 (#502)](https://github.com/elastic/ems-landing-page/pull/502)
=> [v8.5] Bump json5 from 1.0.1 to 1.0.2 (#502)

yarn.lock
- [Bump json5 from 1.0.1 to 1.0.2 (#502)](https://github.com/elastic/ems-landing-page/pull/502)
=> [v7.17] Bump json5 from 1.0.1 to 1.0.2 (#502)

.ci/jobs/defaults.yml, package.json, public/config.json, yarn.lock
Creating this PR pointing to 8.6 so it can be backported to 8.7 and 8.6. I'll create a new PR afterwards to point to 8.7 only to the latest release branch.
Related to https://github.com/elastic/kibana/pull/149331
=> Updates EMS Client to 8.4.0 and points to resources at 8.6

.ci/jobs/defaults.yml, package.json, public/config.json, yarn.lock
- [Updates EMS Client to 8.4.0 and points to resources at 8.6 (#511)](https://github.com/elastic/ems-landing-page/pull/511)
=> [v8.6] Updates EMS Client to 8.4.0 and points to resources at 8.6 (#511)

.ci/jobs/defaults.yml, package.json, public/config.json, yarn.lock
- [Updates EMS Client to 8.4.0 and points to resources at 8.6 (#511)](https://github.com/elastic/ems-landing-page/pull/511)
=> [v8.7] Updates EMS Client to 8.4.0 and points to resources at 8.6 (#511)

public/config.json
Sets 8.7 as the EMS version to point API resources.
Leaving the 8.6 as the default for the root of <maps.elastic.co> until release.
=> Set 8.7 as supported EMS Version

public/config.json
- [Set 8.7 as supported EMS Version (#514)](https://github.com/elastic/ems-landing-page/pull/514)
=> [v8.7] Set 8.7 as supported EMS Version (#514)

package.json, yarn.lock
To merge after #516 
Fixes #510 
Upgrades to the latest version of EUI and removes the resolutions section of the `package.json` since we don't need to enforce (for the moment) any package versions.
=> Update to EUI 74

package.json, yarn.lock
- [Upgrade EUI and remove resolutions (#517)](https://github.com/elastic/ems-landing-page/pull/517)
=> [v8.6] Upgrade EUI and remove resolutions (#517)

package.json, yarn.lock
- [Upgrade EUI and remove resolutions (#517)](https://github.com/elastic/ems-landing-page/pull/517)
=> [v8.7] Upgrade EUI and remove resolutions (#517)

build.sh, deployStaging.sh
Fixing a couple of issues related to EMS Landing Page build
- Update the build script to use node 18 docker image
- Add exclude pattern for rsync to the root branch
About the second, to validate that the exclusion regex on the `rsync`  command works as expected, I run something similar to this on a python environment:
```
>>> import re
>>> 
>>> tests = [
...     'index.html', 'assets/index.html',
...     'vsomething', 'vsomething/something',
...     'v2/index.html', 'v7.0/index.html',
...     'v7.17/index.html',
... ]
>>> 
>>> for test in tests:
...   search = re.search('^v[\d.]+\/.*$',test)
...   result = "❌" if search else "✅"
...   print(f"{result} {test}")
... 
✅ index.html
✅ assets/index.html
✅ vsomething
✅ vsomething/something
❌ v2/index.html
❌ v7.0/index.html
❌ v7.17/index.html
>>> …
```
=> Fix build node image and GCP bukect sync

build.sh, deployStaging.sh
- [Fix build node image and GCP bukect sync (#522)](https://github.com/elastic/ems-landing-page/pull/522)
=> [v8.7] Fix build node image and GCP bukect sync (#522)

build.sh, deployStaging.sh
- [Fix build node image and GCP bukect sync (#522)](https://github.com/elastic/ems-landing-page/pull/522)
=> [v8.6] Fix build node image and GCP bukect sync (#522)

.backportrc.json, .ci/jobs/elastic+ems-landing-page+v8.8.yml, build.sh, package.json
* Bumps `package.json` to 8.8.0
* Adds the `v8.8` branch to the backport config (the branch will be created after this PR is merged)
* Removes CI jobs for 8.5 and creates the job for 8.8
* Removes `npm` config from build
=> Bump to 8.8

package.json, yarn.lock
- [fix: upgrade @elastic/eui from 74.0.1 to 74.1.0 (#526)](https://github.com/elastic/ems-landing-page/pull/526)
=> [v8.6] fix: upgrade @elastic/eui from 74.0.1 to 74.1.0 (#526)

package.json, yarn.lock
- [fix: upgrade @elastic/eui from 74.0.1 to 74.1.0 (#526)](https://github.com/elastic/ems-landing-page/pull/526)
=> [v8.7] fix: upgrade @elastic/eui from 74.0.1 to 74.1.0 (#526)

package.json, yarn.lock
- [fix: upgrade @elastic/eui from 74.0.1 to 74.1.0 (#526)](https://github.com/elastic/ems-landing-page/pull/526)
=> [v8.8] fix: upgrade @elastic/eui from 74.0.1 to 74.1.0 (#526)

yarn.lock
- [Bump webpack from 5.75.0 to 5.76.0 (#529)](https://github.com/elastic/ems-landing-page/pull/529)
=> [v8.6] Bump webpack from 5.75.0 to 5.76.0 (#529)

package.json, yarn.lock
- [fix: upgrade @emotion/css from 11.10.5 to 11.10.6 (#527)](https://github.com/elastic/ems-landing-page/pull/527)
=> [v8.8] fix: upgrade @emotion/css from 11.10.5 to 11.10.6 (#527)

package.json, yarn.lock
- [fix: upgrade @emotion/css from 11.10.5 to 11.10.6 (#527)](https://github.com/elastic/ems-landing-page/pull/527)
=> [v8.7] fix: upgrade @emotion/css from 11.10.5 to 11.10.6 (#527)

yarn.lock
- [Bump webpack from 5.75.0 to 5.76.0 (#529)](https://github.com/elastic/ems-landing-page/pull/529)
=> [v8.8] Bump webpack from 5.75.0 to 5.76.0 (#529)

yarn.lock
- [Bump webpack from 5.75.0 to 5.76.0 (#529)](https://github.com/elastic/ems-landing-page/pull/529)
=> [v8.7] Bump webpack from 5.75.0 to 5.76.0 (#529)

package.json, yarn.lock
This PR upgrades to the latest version of the `favicons` library, addressing a prototype pollution vulnerability found in the `xml2js` package CVE-2023-0842
It also upgrades the `yarn.lock` file with the following list, also addressing a vulnerability found in `terser` CVE-2022-25858 (dependency from `webpack` and `html-webpack-plugin`.
```
@babel/cli@7.21.0
@babel/core@7.21.4
@babel/preset-env@7.21.4
@emotion/react@11.10.6
babel-plugin-inline-react-svg@2.0.2
core-js@3.30.1
eslint@8.38.0
eslint-plugin-react@7.32.2
html-webpack-plugin@5.5.1
webpack@5.80.0
webpack-dev-server@4.13.3
```
=> Upgrade favicons, babel plugins, webpack, eslint, core-js

package.json, yarn.lock
- [Upgrade favicons, babel plugins, webpack, eslint, core-js (#555)](https://github.com/elastic/ems-landing-page/pull/555)
=> [v8.8] Upgrade favicons, babel plugins, webpack, eslint, core-js (#555)

package.json, yarn.lock
- [Upgrade favicons, babel plugins, webpack, eslint, core-js (#555)](https://github.com/elastic/ems-landing-page/pull/555)
=> [v8.7] Upgrade favicons, babel plugins, webpack, eslint, core-js (#555)

package.json, yarn.lock
Introduces a resolution for the `yaml` package (transitive from other dependencies) to the last `2.2.2` release.
=> Add yaml resolution for 2.2.2

.buildkite/pipeline.yml
This PR changes the agent for the buildkite CI system. This PR needs to be backported and adjusted for the `v7.17` branch to use the `-node16` docker image.
We may be able to use [dynamic pipelines](https://buildkite.com/blog/how-to-build-ci-cd-pipelines-dynamically) to set up an initial step that dynamically generates the `build` step pointing to the appropriate agent image but I don't think it is necessary at this point.
=> Upgrade to the new node18 agent, with a tagged version

package.json, yarn.lock
- [Add yaml resolution for 2.2.2 (#558)](https://github.com/elastic/ems-landing-page/pull/558)
=> [v8.9] Add yaml resolution for 2.2.2 (#558)

package.json, yarn.lock
- [Add yaml resolution for 2.2.2 (#558)](https://github.com/elastic/ems-landing-page/pull/558)
=> [v8.7] Add yaml resolution for 2.2.2 (#558)

.buildkite/pipeline.yml
- [Upgrade to the new node18 agent, with a tagged version (#565)](https://github.com/elastic/ems-landing-page/pull/565)
=> [v8.9] Upgrade to the new node18 agent, with a tagged version (#565)

.buildkite/pipeline.yml
- [Upgrade to the new node18 agent, with a tagged version (#565)](https://github.com/elastic/ems-landing-page/pull/565)
=> [v8.8] Upgrade to the new node18 agent, with a tagged version (#565)

.buildkite/pipeline.yml
- [Upgrade to the new node18 agent, with a tagged version (#565)](https://github.com/elastic/ems-landing-page/pull/565)
=> [v8.7] Upgrade to the new node18 agent, with a tagged version (#565)

.buildkite/pipeline.yml
- [Upgrade to the new node18 agent, with a tagged version (#565)](https://github.com/elastic/ems-landing-page/pull/565)
=> [v7.17] Upgrade to the new node18 agent, with a tagged version (#565)

package.json, yarn.lock
- [Add yaml resolution for 2.2.2 (#558)](https://github.com/elastic/ems-landing-page/pull/558)
=> [v7.17] Add yaml resolution for 2.2.2 (#558)

.buildkite/pipeline.yml, .buildkite/scripts/upload.sh
When executing a build from a tag, Buildkite does not provide an environment variable for the source branch the tag is coming from. On the other hand, `build.branch` in the pipeline for tag builds points to the tag name. This forces two changes in our code:
* Fix the `if` condition to check the tag name against our tagging schemas: SemVer and very soon also dates (`yyyy-mm-dd`)
* Fix the value of the `BRANCH` variable for production deployments, extracting the original branch combining `git show` and `sed`
=> [ci] Fix environment for deploy execution

.buildkite/pipeline.yml, .buildkite/scripts/upload.sh
- [[ci] Fix environment for deploy execution (#580)](https://github.com/elastic/ems-landing-page/pull/580)
=> [v7.17] [ci] Fix environment for deploy execution (#580)

.buildkite/scripts/archive.sh
- [Reduces verbosity of archive download and compression commands (#582)](https://github.com/elastic/ems-landing-page/pull/582)
=> [v7.17] Reduces verbosity of archive download and compression commands (#582)

.buildkite/pipeline.yml, .buildkite/scripts/archive.sh, .buildkite/scripts/upload.sh
- [[ci] Fix environment for deploy execution (#580)](https://github.com/elastic/ems-landing-page/pull/580)
- [Reduces verbosity of archive download and compression commands (#582)](https://github.com/elastic/ems-landing-page/pull/582)
=> [v8.8] [ci] Fix environment for deploy execution (#580) | Reduces verbosity of archive download and compression commands (#582)

.buildkite/pipeline.yml, .buildkite/scripts/archive.sh, .buildkite/scripts/upload.sh
- [[ci] Fix environment for deploy execution (#580)](https://github.com/elastic/ems-landing-page/pull/580)
- [Reduces verbosity of archive download and compression commands (#582)](https://github.com/elastic/ems-landing-page/pull/582)
=> [v8.9] [ci] Fix environment for deploy execution (#580) | Reduces verbosity of archive download and compression commands (#582)

package.json, yarn.lock
Upgrades
* `@babel/cli@7.21.5`
* `@babel/core@7.21.8`
* `@babel/preset-env@7.21.5`
* `@emotion/css@11.11.0`
* `@emotion/react@11.11.0`
* `core-js@3.30.2`
* `eslint@8.40.0`
* `webpack-cli@5.1.1`
* `webpack-dev-server@4.15.0`
* `webpack@5.82.1`
~~And adds a explicit dependency from `favicons`: `shapr@^0.32.1`.~~
=> Upgrade for core-js, emotion/css, eslint, webpack

.backportrc.json
- [Remove default for backporting to 8.7 (#598)](https://github.com/elastic/ems-landing-page/pull/598)
=> [v8.9] Remove default for backporting to 8.7 (#598)

.backportrc.json
- [Remove default for backporting to 8.7 (#598)](https://github.com/elastic/ems-landing-page/pull/598)
=> [v8.8] Remove default for backporting to 8.7 (#598)

.backportrc.json
- [Remove default for backporting to 8.7 (#598)](https://github.com/elastic/ems-landing-page/pull/598)
=> [v7.17] Remove default for backporting to 8.7 (#598)

yarn.lock
- [Upgrade for core-js, emotion/css, eslint, webpack (#594)](https://github.com/elastic/ems-landing-page/pull/594)
=> [v8.9] Upgrade for core-js, emotion/css, eslint, webpack (#594)

CONTRIBUTING.md, README.md
This finishes the migration to Buildkite with some documentation on how the build and deployment to staging and production works.
=> [Docs][ci] Update the documentation about buildkite

CONTRIBUTING.md, README.md
- [[Docs][ci] Update the documentation about buildkite (#602)](https://github.com/elastic/ems-landing-page/pull/602)
=> [v8.8] [Docs][ci] Update the documentation about buildkite (#602)

CONTRIBUTING.md, README.md
- [[Docs][ci] Update the documentation about buildkite (#602)](https://github.com/elastic/ems-landing-page/pull/602)
=> [v7.17] [Docs][ci] Update the documentation about buildkite (#602)

CONTRIBUTING.md, README.md
- [[Docs][ci] Update the documentation about buildkite (#602)](https://github.com/elastic/ems-landing-page/pull/602)
=> [v8.9] [Docs][ci] Update the documentation about buildkite (#602)

public/config.json
I failed to update the version on this setting 😭
This forces a new deploy of `8.8` to ensure clients are consuming the correct version of the services.
=> Fix EMS version in config.json

public/config.json
- [Fix EMS version in config.json (#609)](https://github.com/elastic/ems-landing-page/pull/609)
=> [v8.9] Fix EMS version in config.json (#609)

.buildkite/scripts/archive.sh
For some reason we are creating an archive from the staging bucket when we should archive our production environment instead.
=> Archive from production bucket

.buildkite/scripts/archive.sh
- [Archive from production bucket (#612)](https://github.com/elastic/ems-landing-page/pull/612)
=> [v8.9] Archive from production bucket (#612)

.buildkite/scripts/archive.sh
- [Archive from production bucket (#612)](https://github.com/elastic/ems-landing-page/pull/612)
=> [v8.8] Archive from production bucket (#612)

.buildkite/scripts/archive.sh
- [Archive from production bucket (#612)](https://github.com/elastic/ems-landing-page/pull/612)
=> [v7.17] Archive from production bucket (#612)

.buildkite/hooks/pre-command
- [Make 8.8 the default branch (#616)](https://github.com/elastic/ems-landing-page/pull/616)
=> [v8.9] Make 8.8 the default branch (#616)

.buildkite/hooks/pre-command
- [Make 8.8 the default branch (#616)](https://github.com/elastic/ems-landing-page/pull/616)
=> [v8.8] Make 8.8 the default branch (#616)

.buildkite/hooks/pre-command
- [Make 8.8 the default branch (#616)](https://github.com/elastic/ems-landing-page/pull/616)
=> [v7.17] Make 8.8 the default branch (#616)

yarn.lock
> :warning: holding on merging this until `8.8` version of the stack is released.
- [Upgrade for core-js, emotion/css, eslint, webpack (#594)](https://github.com/elastic/ems-landing-page/pull/594)
=> [v8.8] Upgrade for core-js, emotion/css, eslint, webpack (#594)

package.json, yarn.lock
- [Upgrade resolutions to semver 7.5.3 (#623)](https://github.com/elastic/ems-landing-page/pull/623)
=> [v8.9] Upgrade resolutions to semver 7.5.3 (#623)

package.json, yarn.lock
- [Upgrade resolutions to semver 7.5.3 (#623)](https://github.com/elastic/ems-landing-page/pull/623)
=> [v8.10] Upgrade resolutions to semver 7.5.3 (#623)

package.json, yarn.lock
- [Upgrade resolutions to semver 7.5.3 (#623)](https://github.com/elastic/ems-landing-page/pull/623)
=> [v8.8] Upgrade resolutions to semver 7.5.3 (#623)

package.json, yarn.lock
- [Upgrade resolutions to semver 7.5.3 (#623)](https://github.com/elastic/ems-landing-page/pull/623)
=> [v7.17] Upgrade resolutions to semver 7.5.3 (#623)

package.json, yarn.lock
- [Upgrades Y23W28 (#631)](https://github.com/elastic/ems-landing-page/pull/631)
=> [v8.10] Upgrades Y23W28 (#631)

package.json, yarn.lock
- [Upgrades Y23W28 (#631)](https://github.com/elastic/ems-landing-page/pull/631)
=> [v8.8] Upgrades Y23W28 (#631)

.buildkite/hooks/pre-command, .buildkite/pipeline.yml, CONTRIBUTING.md
Fixes #630
Updates the pipeline to execute the staging and production upload script from both SemVer and `master` branch.
If a tag is created on the `master` branch, this is synchronized with the root of the bucket, effectively making our `master` branch the default UI our users will consume.
In a subsequent PR we will update the instantiation of the EMS Client to point to the root manifests for the Files and Tiles services but as for now, `master` will execute equally to the `v8.10` branch.
=> Update Buildkite to create releases from master to the root folder

.buildkite/hooks/pre-command, .buildkite/pipeline.yml, CONTRIBUTING.md
- [Update Buildkite to create releases from master to the root folder (#636)](https://github.com/elastic/ems-landing-page/pull/636)
=> [v8.10] Update Buildkite to create releases from master to the root folder (#636)

.buildkite/hooks/pre-command, .buildkite/pipeline.yml, CONTRIBUTING.md
- [Update Buildkite to create releases from master to the root folder (#636)](https://github.com/elastic/ems-landing-page/pull/636)
=> [v8.9] Update Buildkite to create releases from master to the root folder (#636)

.buildkite/hooks/pre-command, .buildkite/pipeline.yml, CONTRIBUTING.md
- [Update Buildkite to create releases from master to the root folder (#636)](https://github.com/elastic/ems-landing-page/pull/636)
=> [v8.8] Update Buildkite to create releases from master to the root folder (#636)

.buildkite/hooks/pre-command, .buildkite/pipeline.yml, CONTRIBUTING.md
- [Update Buildkite to create releases from master to the root folder (#636)](https://github.com/elastic/ems-landing-page/pull/636)
=> [v7.17] Update Buildkite to create releases from master to the root folder (#636)

.buildkite/pipeline.yml
- [Fix buildkite pipeline (#641)](https://github.com/elastic/ems-landing-page/pull/641)
=> [v7.17] Fix buildkite pipeline (#641)

.buildkite/pipeline.yml
- [Fix buildkite pipeline (#641)](https://github.com/elastic/ems-landing-page/pull/641)
=> [v8.8] Fix buildkite pipeline (#641)

.buildkite/pipeline.yml
- [Fix buildkite pipeline (#641)](https://github.com/elastic/ems-landing-page/pull/641)
=> [v8.9] Fix buildkite pipeline (#641)

.buildkite/pipeline.yml
- [Relax condition for deploy (#645)](https://github.com/elastic/ems-landing-page/pull/645)
=> [v8.10] Relax condition for deploy (#645)

.buildkite/pipeline.yml
- [Relax condition for deploy (#645)](https://github.com/elastic/ems-landing-page/pull/645)
=> [v8.9] Relax condition for deploy (#645)

.buildkite/pipeline.yml
- [Relax condition for deploy (#645)](https://github.com/elastic/ems-landing-page/pull/645)
=> [v8.8] Relax condition for deploy (#645)

.buildkite/pipeline.yml
- [Relax condition for deploy (#645)](https://github.com/elastic/ems-landing-page/pull/645)
=> [v7.17] Relax condition for deploy (#645)

.buildkite/pipeline.yml, .buildkite/scripts/upload.sh
Changes expectation of tagging for deploys to be in the form of `branch-date` as in:
* `master-2023-07-24`
* `v7.17-2023-07-24`
* `v8.10-2023-07-24`
This is defined in the pipeline filter but also used in the script to extract the branch name for the upload.
This PR also includes `master` in the exclusion filter of the `gsutil rsync` so the `/master` folder is kept as the rest of the `vX.Y` folders.
=> Use only the tag name for filtering and fix rsync to skip master

.buildkite/pipeline.yml, .buildkite/scripts/upload.sh
- [Use only the tag name for filtering and fix rsync to skip master (#650)](https://github.com/elastic/ems-landing-page/pull/650)
- fix the regex (64b76a2f)
=> [v8.10] Use only the tag name for filtering and fix rsync to skip master (#650) | fix the regex

.buildkite/pipeline.yml, .buildkite/scripts/upload.sh
- [Use only the tag name for filtering and fix rsync to skip master (#650)](https://github.com/elastic/ems-landing-page/pull/650)
- fix the regex (64b76a2f)
=> [v8.9] Use only the tag name for filtering and fix rsync to skip master (#650) | fix the regex

.buildkite/pipeline.yml, .buildkite/scripts/upload.sh
- [Use only the tag name for filtering and fix rsync to skip master (#650)](https://github.com/elastic/ems-landing-page/pull/650)
- fix the regex (64b76a2f)
=> [v8.8] Use only the tag name for filtering and fix rsync to skip master (#650) | fix the regex

.buildkite/pipeline.yml, .buildkite/scripts/upload.sh
- [Use only the tag name for filtering and fix rsync to skip master (#650)](https://github.com/elastic/ems-landing-page/pull/650)
- fix the regex (64b76a2f)
=> [v7.17] Use only the tag name for filtering and fix rsync to skip master (#650) | fix the regex

CONTRIBUTING.md
This PR updates the documentation to reflect the latest changes in how the EMS Landing Page is deployed since `master` is now the branch that is deployed at `maps.elastic.co` and Stack versions will go only to their corresponding branches.
Related to #630, #650, #645, #641, and #636
=> Updating the contributing documentation

CONTRIBUTING.md
- [Updating the contributing documentation (#655)](https://github.com/elastic/ems-landing-page/pull/655)
=> [v7.17] Updating the contributing documentation (#655)

CONTRIBUTING.md
- [Updating the contributing documentation (#655)](https://github.com/elastic/ems-landing-page/pull/655)
=> [v8.8] Updating the contributing documentation (#655)

.backportrc.json
- Remove 8.8 from backporting (#660) (4ac92161)
=> [v8.9] Remove 8.8 from backporting (#660)

.backportrc.json
- Remove 8.8 from backporting (#660) (4ac92161)
=> [v8.10] Remove 8.8 from backporting (#660)

.backportrc.json, package.json, public/config.json
Bumps the master branch to 8.12 following the [New release docs](https://github.com/elastic/ems-landing-page/blob/4ac92161e4bc8e1eb82a0d98ea14ccf047ad21e2/CONTRIBUTING.md#new-releases)
- Updates the package.json to 8.1220
- Updates the EMS version in the config file to 8.12
- Adds the 8.12 branch to the backport
=> Bump to 8.12

package.json, yarn.lock
- [Bump @babel/traverse from 7.16.5 to 7.23.2 (#669)](https://github.com/elastic/ems-landing-page/pull/669)
=> [v7.17] Bump @babel/traverse from 7.16.5 to 7.23.2 (#669)

yarn.lock
- [Bump @babel/traverse from 7.16.5 to 7.23.2 (#669)](https://github.com/elastic/ems-landing-page/pull/669)
=> [v8.10] Bump @babel/traverse from 7.16.5 to 7.23.2 (#669)

yarn.lock
- [Bump @babel/traverse from 7.16.5 to 7.23.2 (#669)](https://github.com/elastic/ems-landing-page/pull/669)
=> [v8.12] Bump @babel/traverse from 7.16.5 to 7.23.2 (#669)

package.json, yarn.lock
- [Upgrade whatwg-fetch from 3.6.2 to 3.6.16 (#674)](https://github.com/elastic/ems-landing-page/pull/674)
=> [v8.12] Upgrade whatwg-fetch from 3.6.2 to 3.6.16 (#674)

package.json, yarn.lock
- [Upgrade whatwg-fetch from 3.6.2 to 3.6.16 (#674)](https://github.com/elastic/ems-landing-page/pull/674)
=> [v8.11] Upgrade whatwg-fetch from 3.6.2 to 3.6.16 (#674)

package.json, yarn.lock
- [Upgrade whatwg-fetch from 3.6.2 to 3.6.16 (#674)](https://github.com/elastic/ems-landing-page/pull/674)
=> [v8.10] Upgrade whatwg-fetch from 3.6.2 to 3.6.16 (#674)

package.json, yarn.lock
- [Upgrade whatwg-fetch from 3.6.2 to 3.6.16 (#674)](https://github.com/elastic/ems-landing-page/pull/674)
=> [v7.17] Upgrade whatwg-fetch from 3.6.2 to 3.6.16 (#674)

package.json, public/js/components/app.js, public/main.js, yarn.lock
- [Upgrade EUI, show version on tooltip (#680)](https://github.com/elastic/ems-landing-page/pull/680)
=> [v8.11] Upgrade EUI, show version on tooltip (#680)

package.json, public/js/components/app.js, public/main.js, yarn.lock
- [Upgrade EUI, show version on tooltip (#680)](https://github.com/elastic/ems-landing-page/pull/680)
=> [v8.10] Upgrade EUI, show version on tooltip (#680)

public/main.js, yarn.lock
- [Upgrade EUI, show version on tooltip (#680)](https://github.com/elastic/ems-landing-page/pull/680)
=> [v7.17] Show version on tooltip (#680)

package.json, yarn.lock
Updates performed automatically with `yarn upgrade-interactive`
* `@babel/cli@7.23.0`
* `@babel/core@7.23.2`
* `@babel/preset-env@7.23.2`
* `@babel/preset-react@7.22.15`
* `core-js@3.33.0`
* `eslint-plugin-react@7.33.2`
* `eslint@8.51.0`
* `favicons-webpack-plugin@6.0.1`
* `favicons@7.1.4`
* `handlebars@4.7.8`
* `url@0.11.3`
* `webpack-merge@5.10.0`
* `webpack@5.89.0`
=> Update yarn.lock via upgrade-interactive

package.json, yarn.lock
- [Update yarn.lock via upgrade-interactive (#681)](https://github.com/elastic/ems-landing-page/pull/681)
=> [v8.12] Update yarn.lock via upgrade-interactive (#681)

package.json, yarn.lock
- [Update yarn.lock via upgrade-interactive (#681)](https://github.com/elastic/ems-landing-page/pull/681)
=> [v8.11] Update yarn.lock via upgrade-interactive (#681)

package.json, yarn.lock
- [Update yarn.lock via upgrade-interactive (#681)](https://github.com/elastic/ems-landing-page/pull/681)
=> [v8.10] Update yarn.lock via upgrade-interactive (#681)

package.json, yarn.lock
- [Update yarn.lock via upgrade-interactive (#681)](https://github.com/elastic/ems-landing-page/pull/681)
=> [v7.17] Update yarn.lock via upgrade-interactive (#681)

.buildkite/scripts/build.sh, .buildkite/scripts/serverless.js, .buildkite/scripts/serverless.mjs, package.json, yarn.lock
Fixes #668
Part of https://github.com/elastic/kibana/issues/157094
* Updates `ems-client@8.5.0` that accepts date based `emsVersion` parameter to point to `/later/manifest` resources instead of SemVer
* Adds a step in the Buildkite script that calls to the `.buildkite/scripts/serverless.mjs` script to get the current date version from the EMS Tile manifest and changes the default SemVer value in the `config.json` file.
I preferred to do this with a node script because the base image is very limited and this option provides more control and better error handling instead of hacking with UNIX tooling (`sed`, `cat`, etc).
> **Note**
> Even though this code is meant to run only on `master`, I put this PR to backport to all active branches because Buildkite runs code per branch, as opposed to …
=> Update emsVersion in the config.json file when running on master branch

.buildkite/scripts/build.sh, public/config.json, public/main.js
- [[Buikite] Fix version and branch checks (#694)](https://github.com/elastic/ems-landing-page/pull/694)
=> [v8.10] [Buikite] Fix version and branch checks (#694)

.buildkite/scripts/build.sh, public/config.json, public/main.js
- [[Buikite] Fix version and branch checks (#694)](https://github.com/elastic/ems-landing-page/pull/694)
=> [v7.17] [Buikite] Fix version and branch checks (#694)

.buildkite/pipeline.yml, .nvmrc, package.json, yarn.lock
Follow up from https://github.com/elastic/ems-client/pull/208 upstream to upgrade this repo to use Node 20 engine with the necessary updates.
=> Upgrade to Node 20

.buildkite/pipeline.yml, .nvmrc, package.json, yarn.lock
- [Upgrade to Node 20 (#699)](https://github.com/elastic/ems-landing-page/pull/699)
=> [v8.12] Upgrade to Node 20 (#699)

.buildkite/pipeline.yml, .nvmrc, package.json, yarn.lock
- [Upgrade to Node 20 (#699)](https://github.com/elastic/ems-landing-page/pull/699)
=> [v8.11] Upgrade to Node 20 (#699)

.buildkite/pipeline.yml, .nvmrc, package.json, yarn.lock
- [Upgrade to Node 20 (#699)](https://github.com/elastic/ems-landing-page/pull/699)
=> [v7.17] Upgrade to Node 20 (#699)

.backportrc.json, package.json, public/config.json
Bumps the master branch to 8.13 following the [New release docs](https://github.com/elastic/ems-landing-page/blob/4ac92161e4bc8e1eb82a0d98ea14ccf047ad21e2/CONTRIBUTING.md#new-releases)
- Updates the package.json to 8.13.0
- Updates the EMS version in the config file to 8.13
- Adds the 8.13 branch to the backport
=> Bump to 8.13

yarn.lock
- [Bump follow-redirects from 1.15.2 to 1.15.4 (#705)](https://github.com/elastic/ems-landing-page/pull/705)
=> [v8.11] Bump follow-redirects from 1.15.2 to 1.15.4 (#705)

yarn.lock
- [Bump follow-redirects from 1.15.2 to 1.15.4 (#705)](https://github.com/elastic/ems-landing-page/pull/705)
=> [v8.12] Bump follow-redirects from 1.15.2 to 1.15.4 (#705)

yarn.lock
- [Bump follow-redirects from 1.15.2 to 1.15.4 (#705)](https://github.com/elastic/ems-landing-page/pull/705)
=> [v8.13] Bump follow-redirects from 1.15.2 to 1.15.4 (#705)

public/js/components/app.js
Depending on the EMS File Service API used to instantiate the client, the frontend will render a link
* To the root of the server if running against an external endpoint (current behavior)
* To the parent of the current URL if running aganist an internal endpoint (for local installations of EMS)
=> Change the link in logo depending on the file API URL

public/js/components/app.js
- [Change the link in logo depending on the file API URL (#712)](https://github.com/elastic/ems-landing-page/pull/712)
=> [v7.17] Change the link in logo depending on the file API URL (#712)

public/js/components/app.js
- [Change the link in logo depending on the file API URL (#712)](https://github.com/elastic/ems-landing-page/pull/712)
=> [v8.12] Change the link in logo depending on the file API URL (#712)

public/js/components/app.js
- [Change the link in logo depending on the file API URL (#712)](https://github.com/elastic/ems-landing-page/pull/712)
=> [v8.13] Change the link in logo depending on the file API URL (#712)

public/js/components/app.js
- [Change the link in logo depending on the file API URL (#712)](https://github.com/elastic/ems-landing-page/pull/712)
=> [v8.14] Change the link in logo depending on the file API URL (#712)

yarn.lock
- [Bump follow-redirects from 1.15.4 to 1.15.6 (#722)](https://github.com/elastic/ems-landing-page/pull/722)
=> [v8.14] Bump follow-redirects from 1.15.4 to 1.15.6 (#722)

yarn.lock
- [Bump follow-redirects from 1.15.4 to 1.15.6 (#722)](https://github.com/elastic/ems-landing-page/pull/722)
=> [v8.13] Bump follow-redirects from 1.15.4 to 1.15.6 (#722)

yarn.lock
- [Bump webpack-dev-middleware from 7.0.0 to 7.1.1 (#726)](https://github.com/elastic/ems-landing-page/pull/726)
=> [v8.14] Bump webpack-dev-middleware from 7.0.0 to 7.1.1 (#726)

yarn.lock
- [Bump webpack-dev-middleware from 7.0.0 to 7.1.1 (#726)](https://github.com/elastic/ems-landing-page/pull/726)
=> [v8.13] Bump webpack-dev-middleware from 7.0.0 to 7.1.1 (#726)

yarn.lock
- [Bump webpack-dev-middleware from 7.0.0 to 7.1.1 (#726)](https://github.com/elastic/ems-landing-page/pull/726)
=> [v8.12] Bump webpack-dev-middleware from 7.0.0 to 7.1.1 (#726)

yarn.lock
- [Bump webpack-dev-middleware from 7.0.0 to 7.1.1 (#726)](https://github.com/elastic/ems-landing-page/pull/726)
=> [v7.17] Bump webpack-dev-middleware from 7.0.0 to 7.1.1 (#726)

.backportrc.json
- [Remove 8.12 from backport settings (#736)](https://github.com/elastic/ems-landing-page/pull/736)
=> [v7.17] Remove 8.12 from backport settings (#736)

.backportrc.json
- [Remove 8.12 from backport settings (#736)](https://github.com/elastic/ems-landing-page/pull/736)
=> [v8.13] Remove 8.12 from backport settings (#736)

.backportrc.json
- [Remove 8.12 from backport settings (#736)](https://github.com/elastic/ems-landing-page/pull/736)
=> [v8.14] Remove 8.12 from backport settings (#736)

yarn.lock
- [Bump express from 4.18.2 to 4.19.2 (#732)](https://github.com/elastic/ems-landing-page/pull/732)
=> [v8.14] Bump express from 4.18.2 to 4.19.2 (#732)

yarn.lock
- [Bump express from 4.18.2 to 4.19.2 (#732)](https://github.com/elastic/ems-landing-page/pull/732)
=> [v8.13] Bump express from 4.18.2 to 4.19.2 (#732)

yarn.lock
- [Bump express from 4.18.2 to 4.19.2 (#732)](https://github.com/elastic/ems-landing-page/pull/732)
=> [v7.17] Bump express from 4.18.2 to 4.19.2 (#732)

public/js/components/app.js, public/js/components/map.js
In order to get the correct link to put in the page header for self-hosted EMS deployments, compare the location of the current window with the URL passed by EMS Client.
=> Use hostname to get the link logo

public/js/components/app.js, public/js/components/map.js
- [Use hostname to get the link logo (#741)](https://github.com/elastic/ems-landing-page/pull/741)
=> [v8.14] Use hostname to get the link logo (#741)

public/js/components/app.js, public/js/components/map.js
- [Use hostname to get the link logo (#741)](https://github.com/elastic/ems-landing-page/pull/741)
=> [v8.13] Use hostname to get the link logo (#741)

public/js/components/app.js
- [Use hostname to get the link logo (#741)](https://github.com/elastic/ems-landing-page/pull/741)
=> [v7.17] Use hostname to get the link logo (#741)

.backportrc.json, package.json, public/config.json
Bumps the master branch to 8.15 following the [New release docs](https://github.com/elastic/ems-landing-page/blob/4ac92161e4bc8e1eb82a0d98ea14ccf047ad21e2/CONTRIBUTING.md#new-releases)
- Updates the package.json to 8.15.0
- Updates the EMS version in the config file to 8.15
- Adds the 8.15 branch to the backport
=> Bump to 8.15

public/main.js
Small change to start using `createRoot` from `react-dom/client`
Fixes #720
=> refactor: 💡 Use createRoot (React 18)

public/main.js
- [refactor: 💡 Use createRoot (React 18) (#746)](https://github.com/elastic/ems-landing-page/pull/746)
=> [v8.15] refactor: 💡 Use createRoot (React 18) (#746)

public/main.js
- [refactor: 💡 Use createRoot (React 18) (#746)](https://github.com/elastic/ems-landing-page/pull/746)
=> [v8.14] refactor: 💡 Use createRoot (React 18) (#746)

public/main.js
- [refactor: 💡 Use createRoot (React 18) (#746)](https://github.com/elastic/ems-landing-page/pull/746)
=> [v7.17] refactor: 💡 Use createRoot (React 18) (#746)

yarn.lock
- [Bump braces from 3.0.2 to 3.0.3 (#751)](https://github.com/elastic/ems-landing-page/pull/751)
=> [v7.17] Bump braces from 3.0.2 to 3.0.3 (#751)

yarn.lock
- [Bump braces from 3.0.2 to 3.0.3 (#751)](https://github.com/elastic/ems-landing-page/pull/751)
=> [v8.13] Bump braces from 3.0.2 to 3.0.3 (#751)

yarn.lock
- [Bump braces from 3.0.2 to 3.0.3 (#751)](https://github.com/elastic/ems-landing-page/pull/751)
=> [v8.14] Bump braces from 3.0.2 to 3.0.3 (#751)

yarn.lock
- [Bump braces from 3.0.2 to 3.0.3 (#751)](https://github.com/elastic/ems-landing-page/pull/751)
=> [v8.15] Bump braces from 3.0.2 to 3.0.3 (#751)

yarn.lock
- [Bump ws from 8.16.0 to 8.17.1 (#756)](https://github.com/elastic/ems-landing-page/pull/756)
=> [v8.15] Bump ws from 8.16.0 to 8.17.1 (#756)

yarn.lock
- [Bump ws from 8.16.0 to 8.17.1 (#756)](https://github.com/elastic/ems-landing-page/pull/756)
=> [v8.14] Bump ws from 8.16.0 to 8.17.1 (#756)

yarn.lock
- [Bump ws from 8.16.0 to 8.17.1 (#756)](https://github.com/elastic/ems-landing-page/pull/756)
=> [v8.13] Bump ws from 8.16.0 to 8.17.1 (#756)

yarn.lock
- [Bump ws from 8.16.0 to 8.17.1 (#756)](https://github.com/elastic/ems-landing-page/pull/756)
=> [v7.17] Bump ws from 8.16.0 to 8.17.1 (#756)

.backportrc.json, package.json, public/config.json
Bumps the master branch to 8.16 following the [New release docs](https://github.com/elastic/ems-landing-page/blob/4ac92161e4bc8e1eb82a0d98ea14ccf047ad21e2/CONTRIBUTING.md#new-releases)
- Updates the package.json to 8.16.0
- Updates the EMS version in the config file to 8.16
- Adds the 8.16 branch to the backport
=> Bump to 8.16

package.json, webpack.common.js, yarn.lock
- [Upgrade @elastic/ems-client@8.5.3 (#763)](https://github.com/elastic/ems-landing-page/pull/763)
=> [v8.16] Upgrade @elastic/ems-client@8.5.3 (#763)

package.json, webpack.common.js, yarn.lock
- [Upgrade @elastic/ems-client@8.5.3 (#763)](https://github.com/elastic/ems-landing-page/pull/763)
=> [v8.15] Upgrade @elastic/ems-client@8.5.3 (#763)

package.json, webpack.common.js, yarn.lock
- [Upgrade @elastic/ems-client@8.5.3 (#763)](https://github.com/elastic/ems-landing-page/pull/763)
=> [v8.14] Upgrade @elastic/ems-client@8.5.3 (#763)

yarn.lock
- [Bump elliptic from 6.5.6 to 6.5.7 (#772)](https://github.com/elastic/ems-landing-page/pull/772)
=> [v8.16] Bump elliptic from 6.5.6 to 6.5.7 (#772)

yarn.lock
- [Bump elliptic from 6.5.6 to 6.5.7 (#772)](https://github.com/elastic/ems-landing-page/pull/772)
=> [v8.15] Bump elliptic from 6.5.6 to 6.5.7 (#772)

package.json, yarn.lock
- [chore(deps): update dependency url to v0.11.4 (#773)](https://github.com/elastic/ems-landing-page/pull/773)
=> [v8.16] chore(deps): update dependency url to v0.11.4 (#773)

package.json, yarn.lock
- [chore(deps): update dependency webpack-dev-server to v5.0.4 (#774)](https://github.com/elastic/ems-landing-page/pull/774)
=> [v8.16] chore(deps): update dependency webpack-dev-server to v5.0.4 (#774)

package.json, yarn.lock
- [chore(deps): update dependency url to v0.11.4 (#773)](https://github.com/elastic/ems-landing-page/pull/773)
=> [v8.15] chore(deps): update dependency url to v0.11.4 (#773)

package.json, yarn.lock
- [chore(deps): update dependency webpack-dev-server to v5.0.4 (#774)](https://github.com/elastic/ems-landing-page/pull/774)
=> [v8.15] chore(deps): update dependency webpack-dev-server to v5.0.4 (#774)

package.json, yarn.lock
- [chore(deps): update dependency core-js to v3.38.1 (#776)](https://github.com/elastic/ems-landing-page/pull/776)
=> [v8.16] chore(deps): update dependency core-js to v3.38.1 (#776)

package.json, yarn.lock
- [chore(deps): update dependency core-js to v3.38.1 (#776)](https://github.com/elastic/ems-landing-page/pull/776)
=> [v8.15] chore(deps): update dependency core-js to v3.38.1 (#776)

package.json, yarn.lock
- [chore(deps): update dependency eslint to v8.57.0 (#778)](https://github.com/elastic/ems-landing-page/pull/778)
=> [v8.16] chore(deps): update dependency eslint to v8.57.0 (#778)

package.json, yarn.lock
- [chore(deps): update dependency css-loader to v6.11.0 (#777)](https://github.com/elastic/ems-landing-page/pull/777)
=> [v8.15] chore(deps): update dependency css-loader to v6.11.0 (#777)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.35.0 (#779)](https://github.com/elastic/ems-landing-page/pull/779)
=> [v8.16] chore(deps): update dependency eslint-plugin-react to v7.35.0 (#779)

package.json, yarn.lock
- [chore(deps): update dependency husky to v9.1.5 (#780)](https://github.com/elastic/ems-landing-page/pull/780)
=> [v8.16] chore(deps): update dependency husky to v9.1.5 (#780)

package.json, yarn.lock
- [chore(deps): update dependency webpack to v5.93.0 (#782)](https://github.com/elastic/ems-landing-page/pull/782)
=> [v8.16] chore(deps): update dependency webpack to v5.93.0 (#782)

.buildkite/pipeline.yml
- [chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.4 (#783)](https://github.com/elastic/ems-landing-page/pull/783)
=> [v8.16] chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.4 (#783)

package.json, yarn.lock
- [chore(deps): update dependency @babel/preset-env to v7.25.4 (#784)](https://github.com/elastic/ems-landing-page/pull/784)
=> [v8.16] chore(deps): update dependency @babel/preset-env to v7.25.4 (#784)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v93.6.0 (#785)](https://github.com/elastic/ems-landing-page/pull/785)
=> [v8.16] fix(deps): update dependency @elastic/eui to v93.6.0 (#785)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.35.0 (#779)](https://github.com/elastic/ems-landing-page/pull/779)
=> [v8.15] chore(deps): update dependency eslint-plugin-react to v7.35.0 (#779)

package.json, yarn.lock
- [chore(deps): update dependency webpack to v5.93.0 (#782)](https://github.com/elastic/ems-landing-page/pull/782)
=> [v8.15] chore(deps): update dependency webpack to v5.93.0 (#782)

.buildkite/pipeline.yml
- [chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.4 (#783)](https://github.com/elastic/ems-landing-page/pull/783)
=> [v8.15] chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.4 (#783)

package.json, yarn.lock
- [chore(deps): update dependency @babel/preset-env to v7.25.4 (#784)](https://github.com/elastic/ems-landing-page/pull/784)
=> [v8.15] chore(deps): update dependency @babel/preset-env to v7.25.4 (#784)

package.json, yarn.lock
- [chore(deps): update dependency webpack to v5.94.0 (#786)](https://github.com/elastic/ems-landing-page/pull/786)
=> [v8.16] chore(deps): update dependency webpack to v5.94.0 (#786)

package.json, public/js/components/map.js, yarn.lock
- [fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)](https://github.com/elastic/ems-landing-page/pull/787)
=> [v8.16] fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)

package.json, yarn.lock
- [chore(deps): update dependency webpack to v5.94.0 (#786)](https://github.com/elastic/ems-landing-page/pull/786)
=> [v8.15] chore(deps): update dependency webpack to v5.94.0 (#786)

package.json, public/js/components/map.js, yarn.lock
- [fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)](https://github.com/elastic/ems-landing-page/pull/787)
=> [v8.15] fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)

package.json, yarn.lock
- [chore(deps): update dependency webpack to v5.94.0 (#786)](https://github.com/elastic/ems-landing-page/pull/786)
=> [v7.17] chore(deps): update dependency webpack to v5.94.0 (#786)

package.json, public/js/components/map.js, yarn.lock
- [fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)](https://github.com/elastic/ems-landing-page/pull/787)
=> [v7.17] fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)

package.json, public/js/components/map.js, yarn.lock
Reverts elastic/ems-landing-page#787
It seems at this point the latest release of the library is not working on our environment, reverting to get things working until we find a solution.
=> Revert "fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0"

package.json, public/js/components/map.js, yarn.lock
- [Revert &quot;fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)&quot; (#836)](https://github.com/elastic/ems-landing-page/pull/836)
=> [v8.16] Revert "fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)" (#836)

package.json, public/js/components/map.js, yarn.lock
- [Revert &quot;fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)&quot; (#836)](https://github.com/elastic/ems-landing-page/pull/836)
=> [v8.15] Revert "fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)" (#836)

package.json, public/js/components/map.js, yarn.lock
- [Revert &quot;fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)&quot; (#836)](https://github.com/elastic/ems-landing-page/pull/836)
=> [v7.17] Revert "fix(deps): update dependency @mapbox/mapbox-gl-rtl-text to ^0.3.0 (#787)" (#836)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v2.6.0 (#820)](https://github.com/elastic/ems-landing-page/pull/820)
=> [v8.16] fix(deps): update dependency chroma-js to v2.6.0 (#820)

package.json, yarn.lock
- [fix(deps): update emotion monorepo (#828)](https://github.com/elastic/ems-landing-page/pull/828)
=> [v8.16] fix(deps): update emotion monorepo (#828)

package.json, yarn.lock
- [fix(deps): update react monorepo to v18.3.1 (#829)](https://github.com/elastic/ems-landing-page/pull/829)
=> [v8.16] fix(deps): update react monorepo to v18.3.1 (#829)

package.json, yarn.lock
- [chore(deps): update dependency css-loader to v7 (#830)](https://github.com/elastic/ems-landing-page/pull/830)
=> [v8.16] chore(deps): update dependency css-loader to v7 (#830)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v2.6.0 (#820)](https://github.com/elastic/ems-landing-page/pull/820)
=> [v8.15] fix(deps): update dependency chroma-js to v2.6.0 (#820)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v2.6.0 (#820)](https://github.com/elastic/ems-landing-page/pull/820)
=> [v7.17] fix(deps): update dependency chroma-js to v2.6.0 (#820)

package.json, yarn.lock
- [fix(deps): update emotion monorepo (#828)](https://github.com/elastic/ems-landing-page/pull/828)
=> [v8.15] fix(deps): update emotion monorepo (#828)

package.json, yarn.lock
- [fix(deps): update emotion monorepo (#828)](https://github.com/elastic/ems-landing-page/pull/828)
=> [v7.17] fix(deps): update emotion monorepo (#828)

package.json, yarn.lock
- [fix(deps): update react monorepo to v18.3.1 (#829)](https://github.com/elastic/ems-landing-page/pull/829)
=> [v8.15] fix(deps): update react monorepo to v18.3.1 (#829)

package.json, yarn.lock
- [chore(deps): update dependency css-loader to v7 (#830)](https://github.com/elastic/ems-landing-page/pull/830)
=> [v8.15] chore(deps): update dependency css-loader to v7 (#830)

package.json, yarn.lock
- [chore(deps): update dependency css-loader to v7 (#830)](https://github.com/elastic/ems-landing-page/pull/830)
=> [v7.17] chore(deps): update dependency css-loader to v7 (#830)

package.json, yarn.lock
- [fix(deps): update dependency @elastic/eui to v95 (#833)](https://github.com/elastic/ems-landing-page/pull/833)
=> [v8.16] fix(deps): update dependency @elastic/eui to v95 (#833)

package.json, yarn.lock
- [fix(deps): update dependency @elastic/eui to v95 (#833)](https://github.com/elastic/ems-landing-page/pull/833)
=> [v8.15] fix(deps): update dependency @elastic/eui to v95 (#833)

package.json, yarn.lock
- [fix(deps): update dependency @elastic/eui to v95 (#833)](https://github.com/elastic/ems-landing-page/pull/833)
=> [v7.17] fix(deps): update dependency @elastic/eui to v95 (#833)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v3 (#834)](https://github.com/elastic/ems-landing-page/pull/834)
=> [v8.16] fix(deps): update dependency chroma-js to v3 (#834)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v3 (#834)](https://github.com/elastic/ems-landing-page/pull/834)
=> [v8.15] fix(deps): update dependency chroma-js to v3 (#834)

package.json, yarn.lock
- [chore(deps): update dependency style-loader to v4 (#868)](https://github.com/elastic/ems-landing-page/pull/868)
=> [v8.16] chore(deps): update dependency style-loader to v4 (#868)

package.json, yarn.lock
- [chore(deps): update dependency style-loader to v4 (#868)](https://github.com/elastic/ems-landing-page/pull/868)
=> [v8.15] chore(deps): update dependency style-loader to v4 (#868)

package.json, yarn.lock
- [chore(deps): update dependency style-loader to v4 (#868)](https://github.com/elastic/ems-landing-page/pull/868)
=> [v7.17] chore(deps): update dependency style-loader to v4 (#868)

package.json, yarn.lock
- [chore(deps): update dependency webpack-merge to v6 (#869)](https://github.com/elastic/ems-landing-page/pull/869)
=> [v8.16] chore(deps): update dependency webpack-merge to v6 (#869)

package.json, yarn.lock
- [chore(deps): update dependency webpack-merge to v6 (#869)](https://github.com/elastic/ems-landing-page/pull/869)
=> [v7.17] chore(deps): update dependency webpack-merge to v6 (#869)

package.json, yarn.lock
- [chore(deps): update dependency webpack-merge to v6 (#869)](https://github.com/elastic/ems-landing-page/pull/869)
=> [v8.15] chore(deps): update dependency webpack-merge to v6 (#869)

package.json, yarn.lock
- [Update yaml and semver resolutions (#885)](https://github.com/elastic/ems-landing-page/pull/885)
=> [v8.16] Update yaml and semver resolutions (#885)

package.json, yarn.lock
- [Update yaml and semver resolutions (#885)](https://github.com/elastic/ems-landing-page/pull/885)
=> [v8.15] Update yaml and semver resolutions (#885)

package.json, yarn.lock
- [Update yaml and semver resolutions (#885)](https://github.com/elastic/ems-landing-page/pull/885)
=> [v7.17] Update yaml and semver resolutions (#885)

.buildkite/pipeline.yml
- [chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.5 (#893)](https://github.com/elastic/ems-landing-page/pull/893)
=> [v8.16] chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.5 (#893)

.buildkite/pipeline.yml
- [chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.5 (#893)](https://github.com/elastic/ems-landing-page/pull/893)
=> [v8.15] chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.5 (#893)

.buildkite/pipeline.yml
- [chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.5 (#893)](https://github.com/elastic/ems-landing-page/pull/893)
=> [v7.17] chore(deps): update docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20 docker tag to v0.5 (#893)

yarn.lock
- [Bump micromatch from 4.0.5 to 4.0.8 (#897)](https://github.com/elastic/ems-landing-page/pull/897)
=> [v8.16] Bump micromatch from 4.0.5 to 4.0.8 (#897)

yarn.lock
- [Bump micromatch from 4.0.5 to 4.0.8 (#897)](https://github.com/elastic/ems-landing-page/pull/897)
=> [v8.15] Bump micromatch from 4.0.5 to 4.0.8 (#897)

yarn.lock
- [Bump micromatch from 4.0.5 to 4.0.8 (#897)](https://github.com/elastic/ems-landing-page/pull/897)
=> [v7.17] Bump micromatch from 4.0.5 to 4.0.8 (#897)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.9.0 (#905)](https://github.com/elastic/ems-landing-page/pull/905)
=> [v8.16] fix(deps): update dependency @elastic/eui to v95.9.0 (#905)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.9.0 (#905)](https://github.com/elastic/ems-landing-page/pull/905)
=> [v7.17] fix(deps): update dependency @elastic/eui to v95.9.0 (#905)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.9.0 (#905)](https://github.com/elastic/ems-landing-page/pull/905)
=> [v8.15] fix(deps): update dependency @elastic/eui to v95.9.0 (#905)

package.json, yarn.lock
- [chore(deps): update dependency @babel/cli to v7.25.6 (#909)](https://github.com/elastic/ems-landing-page/pull/909)
=> [v8.16] chore(deps): update dependency @babel/cli to v7.25.6 (#909)

package.json, yarn.lock
- [chore(deps): update dependency @babel/cli to v7.25.6 (#909)](https://github.com/elastic/ems-landing-page/pull/909)
=> [v7.17] chore(deps): update dependency @babel/cli to v7.25.6 (#909)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.35.1 (#913)](https://github.com/elastic/ems-landing-page/pull/913)
=> [v7.17] chore(deps): update dependency eslint-plugin-react to v7.35.1 (#913)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.35.1 (#913)](https://github.com/elastic/ems-landing-page/pull/913)
=> [v8.16] chore(deps): update dependency eslint-plugin-react to v7.35.1 (#913)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.35.1 (#913)](https://github.com/elastic/ems-landing-page/pull/913)
=> [v8.15] chore(deps): update dependency eslint-plugin-react to v7.35.1 (#913)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.35.2 (#917)](https://github.com/elastic/ems-landing-page/pull/917)
=> [v8.16] chore(deps): update dependency eslint-plugin-react to v7.35.2 (#917)

package.json, yarn.lock
- [chore(deps): update dependency webpack-dev-server to v5.1.0 (#918)](https://github.com/elastic/ems-landing-page/pull/918)
=> [v8.16] chore(deps): update dependency webpack-dev-server to v5.1.0 (#918)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.10.0 (#922)](https://github.com/elastic/ems-landing-page/pull/922)
=> [v8.16] fix(deps): update dependency @elastic/eui to v95.10.0 (#922)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.35.2 (#917)](https://github.com/elastic/ems-landing-page/pull/917)
=> [v8.15] chore(deps): update dependency eslint-plugin-react to v7.35.2 (#917)

package.json, yarn.lock
- [chore(deps): update dependency webpack-dev-server to v5.1.0 (#918)](https://github.com/elastic/ems-landing-page/pull/918)
=> [v8.15] chore(deps): update dependency webpack-dev-server to v5.1.0 (#918)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.10.0 (#922)](https://github.com/elastic/ems-landing-page/pull/922)
=> [v8.15] fix(deps): update dependency @elastic/eui to v95.10.0 (#922)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.35.2 (#917)](https://github.com/elastic/ems-landing-page/pull/917)
=> [v7.17] chore(deps): update dependency eslint-plugin-react to v7.35.2 (#917)

package.json, yarn.lock
- [chore(deps): update dependency webpack-dev-server to v5.1.0 (#918)](https://github.com/elastic/ems-landing-page/pull/918)
=> [v7.17] chore(deps): update dependency webpack-dev-server to v5.1.0 (#918)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.10.1 (#932)](https://github.com/elastic/ems-landing-page/pull/932)
=> [v8.x] fix(deps): update dependency @elastic/eui to v95.10.1 (#932)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.10.1 (#932)](https://github.com/elastic/ems-landing-page/pull/932)
=> [v7.17] fix(deps): update dependency @elastic/eui to v95.10.1 (#932)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.10.1 (#932)](https://github.com/elastic/ems-landing-page/pull/932)
=> [v8.16] fix(deps): update dependency @elastic/eui to v95.10.1 (#932)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.10.1 (#932)](https://github.com/elastic/ems-landing-page/pull/932)
=> [v8.15] fix(deps): update dependency @elastic/eui to v95.10.1 (#932)

.backportrc.json, package.json, public/config.json, renovate.json
Bumps the master branch to 9.0 following the [New release docs](https://github.com/elastic/ems-landing-page/blob/4ac92161e4bc8e1eb82a0d98ea14ccf047ad21e2/CONTRIBUTING.md#new-releases)
- Updates the package.json to 9.0.0
- Updates the EMS version in the config file to 9.0.0
- Adds the 9.0 branch to the backport and removes 7.17
- Updates renovate.json file
Depends on https://github.com/elastic/ems-file-service/pull/341 (merged)
>[!important]
> After this PR is merged a new `v9.0` sibling branch and initial tag will be created to get the `v9.0` route published in our GCP buckets.
>[!important]
> A `v8.x` branch has already been cut and future backports from `master` will go to `v9.0`, `v8.x`, `v8.17`, `v8.16`, `v8.15`, and `v7.17`. This is **a lot**, we may need to start working on …
=> Bumps to 9.0

package.json, yarn.lock
=> [v9.0] fix(deps): update dependency maplibre-gl to v4.7.0 (#938)

package.json, yarn.lock
=> [v8.x] fix(deps): update dependency maplibre-gl to v4.7.0 (#938)

package.json, yarn.lock
=> [v8.16] fix(deps): update dependency maplibre-gl to v4.7.0 (#938)

package.json, yarn.lock
=> [v8.15] fix(deps): update dependency maplibre-gl to v4.7.0 (#938)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v3.1.1 (#948)](https://github.com/elastic/ems-landing-page/pull/948)
=> [v8.15] fix(deps): update dependency chroma-js to v3.1.1 (#948)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v3.1.1 (#948)](https://github.com/elastic/ems-landing-page/pull/948)
=> [v8.16] fix(deps): update dependency chroma-js to v3.1.1 (#948)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v3.1.1 (#948)](https://github.com/elastic/ems-landing-page/pull/948)
=> [v8.x] fix(deps): update dependency chroma-js to v3.1.1 (#948)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v3.1.1 (#948)](https://github.com/elastic/ems-landing-page/pull/948)
=> [v9.0] fix(deps): update dependency chroma-js to v3.1.1 (#948)

package.json, yarn.lock
=> [v7.17] fix(deps): update dependency maplibre-gl to v4.7.0 (#938)

package.json, yarn.lock
=> [v9.0] chore(deps): update dependency husky to v9.1.6 (#954)

package.json, yarn.lock
=> [v9.0] chore(deps): update dependency eslint-plugin-react to v7.36.1 (#955)

yarn.lock
=> [v9.0] fix(deps): update dependency @elastic/eui to v95.11.0 (#962)

package.json, yarn.lock
=> [v8.x] chore(deps): update dependency husky to v9.1.6 (#954)

package.json, yarn.lock
=> [v8.x] chore(deps): update dependency eslint-plugin-react to v7.36.1 (#955)

yarn.lock
=> [v8.x] fix(deps): update dependency @elastic/eui to v95.11.0 (#962)

package.json, yarn.lock
=> [v8.16] chore(deps): update dependency husky to v9.1.6 (#954)

yarn.lock
=> [v8.16] fix(deps): update dependency @elastic/eui to v95.11.0 (#962)

package.json, yarn.lock
=> [v8.15] chore(deps): update dependency husky to v9.1.6 (#954)

package.json, yarn.lock
=> [v8.15] chore(deps): update dependency eslint-plugin-react to v7.36.1 (#955)

yarn.lock
=> [v8.15] fix(deps): update dependency @elastic/eui to v95.11.0 (#962)

package.json, yarn.lock
=> [v7.17] chore(deps): update dependency husky to v9.1.6 (#954)

package.json, yarn.lock
=> [v7.17] chore(deps): update dependency eslint-plugin-react to v7.36.1 (#955)

yarn.lock
=> [v7.17] fix(deps): update dependency @elastic/eui to v95.11.0 (#962)

package.json, yarn.lock
=> [v8.16] chore(deps): update dependency eslint-plugin-react to v7.36.1 (#955)

package.json, yarn.lock
- [chore(deps): update dependency babel-loader to v9.2.1 (#972)](https://github.com/elastic/ems-landing-page/pull/972)
=> [v9.0] chore(deps): update dependency babel-loader to v9.2.1 (#972)

package.json, yarn.lock
- [chore(deps): update dependency babel-loader to v9.2.1 (#972)](https://github.com/elastic/ems-landing-page/pull/972)
=> [v8.16] chore(deps): update dependency babel-loader to v9.2.1 (#972)

package.json, yarn.lock
- [chore(deps): update dependency babel-loader to v9.2.1 (#972)](https://github.com/elastic/ems-landing-page/pull/972)
=> [v8.15] chore(deps): update dependency babel-loader to v9.2.1 (#972)

package.json, yarn.lock
- [chore(deps): update dependency babel-loader to v9.2.1 (#972)](https://github.com/elastic/ems-landing-page/pull/972)
=> [v7.17] chore(deps): update dependency babel-loader to v9.2.1 (#972)

package.json, yarn.lock
- [fix(deps): update dependency maplibre-gl to v4.7.1 (#984)](https://github.com/elastic/ems-landing-page/pull/984)
=> [v8.x] fix(deps): update dependency maplibre-gl to v4.7.1 (#984)

package.json, yarn.lock
- [fix(deps): update dependency maplibre-gl to v4.7.1 (#984)](https://github.com/elastic/ems-landing-page/pull/984)
=> [v8.16] fix(deps): update dependency maplibre-gl to v4.7.1 (#984)

package.json, yarn.lock
- [fix(deps): update dependency maplibre-gl to v4.7.1 (#984)](https://github.com/elastic/ems-landing-page/pull/984)
=> [v8.15] fix(deps): update dependency maplibre-gl to v4.7.1 (#984)

package.json, yarn.lock
- [fix(deps): update dependency maplibre-gl to v4.7.1 (#984)](https://github.com/elastic/ems-landing-page/pull/984)
=> [v7.17] fix(deps): update dependency maplibre-gl to v4.7.1 (#984)

package.json, yarn.lock
=> [v9.0] chore(deps): update dependency webpack to v5.95.0 (#991)

package.json, yarn.lock
=> [v8.x] chore(deps): update dependency webpack to v5.95.0 (#991)

package.json, yarn.lock
=> [v8.16] chore(deps): update dependency webpack to v5.95.0 (#991)

package.json, yarn.lock
=> [v8.15] chore(deps): update dependency webpack to v5.95.0 (#991)

package.json, yarn.lock
=> [v7.17] chore(deps): update dependency webpack to v5.95.0 (#991)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.12.0 (#1002)](https://github.com/elastic/ems-landing-page/pull/1002)
=> [v9.0] fix(deps): update dependency @elastic/eui to v95.12.0 (#1002)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.12.0 (#1002)](https://github.com/elastic/ems-landing-page/pull/1002)
=> [v8.16] fix(deps): update dependency @elastic/eui to v95.12.0 (#1002)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.12.0 (#1002)](https://github.com/elastic/ems-landing-page/pull/1002)
=> [v8.15] fix(deps): update dependency @elastic/eui to v95.12.0 (#1002)

yarn.lock
- [fix(deps): update dependency @elastic/eui to v95.12.0 (#1002)](https://github.com/elastic/ems-landing-page/pull/1002)
=> [v7.17] fix(deps): update dependency @elastic/eui to v95.12.0 (#1002)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.37.0 (#1008)](https://github.com/elastic/ems-landing-page/pull/1008)
=> [v9.0] chore(deps): update dependency eslint-plugin-react to v7.37.0 (#1008)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.37.0 (#1008)](https://github.com/elastic/ems-landing-page/pull/1008)
=> [v8.16] chore(deps): update dependency eslint-plugin-react to v7.37.0 (#1008)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.37.0 (#1008)](https://github.com/elastic/ems-landing-page/pull/1008)
=> [v8.15] chore(deps): update dependency eslint-plugin-react to v7.37.0 (#1008)

package.json, yarn.lock
- [chore(deps): update dependency eslint-plugin-react to v7.37.0 (#1008)](https://github.com/elastic/ems-landing-page/pull/1008)
=> [v7.17] chore(deps): update dependency eslint-plugin-react to v7.37.0 (#1008)

package.json, yarn.lock
=> [v9.0] chore(deps): update dependency eslint-plugin-react to v7.37.1 (#1015)

package.json, yarn.lock
=> [v8.x] chore(deps): update dependency eslint-plugin-react to v7.37.1 (#1015)

package.json, yarn.lock
- [chore(deps): update dependency globals to v15.10.0 (#1022)](https://github.com/elastic/ems-landing-page/pull/1022)
=> [v8.x] chore(deps): update dependency globals to v15.10.0 (#1022)

package.json, yarn.lock
=> [v8.16] chore(deps): update dependency eslint-plugin-react to v7.37.1 (#1015)

package.json, yarn.lock
- [chore(deps): update dependency globals to v15.10.0 (#1022)](https://github.com/elastic/ems-landing-page/pull/1022)
=> [v8.16] chore(deps): update dependency globals to v15.10.0 (#1022)

package.json, yarn.lock
=> [v8.15] chore(deps): update dependency eslint-plugin-react to v7.37.1 (#1015)

package.json, yarn.lock
- [chore(deps): update dependency globals to v15.10.0 (#1022)](https://github.com/elastic/ems-landing-page/pull/1022)
=> [v8.15] chore(deps): update dependency globals to v15.10.0 (#1022)

package.json, yarn.lock
=> [v7.17] chore(deps): update dependency eslint-plugin-react to v7.37.1 (#1015)

package.json, yarn.lock
- [chore(deps): update dependency globals to v15.10.0 (#1022)](https://github.com/elastic/ems-landing-page/pull/1022)
=> [v7.17] chore(deps): update dependency globals to v15.10.0 (#1022)

package.json, public/main.css, yarn.lock
=> [v8.x] fix(deps): update dependency @elastic/eui to v96 (#1039)

package.json, public/main.css, yarn.lock
=> [v9.0] fix(deps): update dependency @elastic/eui to v96 (#1039)

package.json, public/main.css, yarn.lock
=> [v8.15] fix(deps): update dependency @elastic/eui to v96 (#1039)

package.json, public/main.css, yarn.lock
=> [v8.16] fix(deps): update dependency @elastic/eui to v96 (#1039)

package.json, public/main.css, yarn.lock
=> [v7.17] fix(deps): update dependency @elastic/eui to v96 (#1039)

package.json, yarn.lock
=> [v9.0] chore(deps): update dependency globals to v15.11.0 (#1056)

package.json, yarn.lock
=> [v9.0] fix(deps): update dependency @elastic/eui to v97 (#1057)

package.json, yarn.lock
=> [v8.x] chore(deps): update dependency globals to v15.11.0 (#1056)

package.json, yarn.lock
=> [v8.x] fix(deps): update dependency @elastic/eui to v97 (#1057)

package.json, yarn.lock
=> [v8.15] chore(deps): update dependency globals to v15.11.0 (#1056)

package.json, yarn.lock
=> [v8.15] fix(deps): update dependency @elastic/eui to v97 (#1057)

package.json, yarn.lock
=> [v8.16] chore(deps): update dependency globals to v15.11.0 (#1056)

package.json, yarn.lock
=> [v8.16] fix(deps): update dependency @elastic/eui to v97 (#1057)

package.json, yarn.lock
=> [v7.17] chore(deps): update dependency globals to v15.11.0 (#1056)

package.json, yarn.lock
=> [v7.17] fix(deps): update dependency @elastic/eui to v97 (#1057)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v3.1.2 (#1069)](https://github.com/elastic/ems-landing-page/pull/1069)
=> [v9.0] fix(deps): update dependency chroma-js to v3.1.2 (#1069)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v3.1.2 (#1069)](https://github.com/elastic/ems-landing-page/pull/1069)
=> [v8.x] fix(deps): update dependency chroma-js to v3.1.2 (#1069)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v3.1.2 (#1069)](https://github.com/elastic/ems-landing-page/pull/1069)
=> [v8.15] fix(deps): update dependency chroma-js to v3.1.2 (#1069)

package.json, yarn.lock
- [fix(deps): update dependency chroma-js to v3.1.2 (#1069)](https://github.com/elastic/ems-landing-page/pull/1069)
=> [v8.16] fix(deps): update dependency chroma-js to v3.1.2 (#1069)

yarn.lock
=> [v9.0] fix(deps): update dependency @elastic/eui to v97.1.0 (#1079)

yarn.lock
=> [v8.x] fix(deps): update dependency @elastic/eui to v97.1.0 (#1079)

yarn.lock
=> [v8.15] fix(deps): update dependency @elastic/eui to v97.1.0 (#1079)

yarn.lock
=> [v8.16] fix(deps): update dependency @elastic/eui to v97.1.0 (#1079)

yarn.lock
=> [v7.17] fix(deps): update dependency @elastic/eui to v97.1.0 (#1079)

.backportrc.json, package.json, public/config.json, renovate.json
Bumps the master branch to 8.17 following the [New release docs](https://github.com/elastic/ems-landing-page/blob/4ac92161e4bc8e1eb82a0d98ea14ccf047ad21e2/CONTRIBUTING.md#new-releases)
- Updates the package.json to 8.17.0
- Updates the EMS version in the config file to 8.17
- Adds the 8.17 branch to the backport
- Updates renovate.json
>[!Important]
> In preparation of the new `v9.x` series. This PR is against the `v8.x` branch
>[!Important]
> After this PR is merged a sibling `v8.17` branch synchronized with `v8.x` will be created to deploy a new version in the `v8.17` route in our GCP buckets.
=> Bumps to 8.17

package.json, yarn.lock
=> [v9.0] chore(deps): update dependency html-webpack-plugin to v5.6.2 (#1085)

package.json, yarn.lock
=> [v8.x] chore(deps): update dependency html-webpack-plugin to v5.6.2 (#1085)

package.json, yarn.lock
=> [v8.17] chore(deps): update dependency html-webpack-plugin to v5.6.2 (#1085)

package.json, yarn.lock
=> [v8.16] chore(deps): update dependency html-webpack-plugin to v5.6.2 (#1085)

package.json, yarn.lock
=> [v8.15] chore(deps): update dependency html-webpack-plugin to v5.6.2 (#1085)

package.json, yarn.lock
=> [v7.17] chore(deps): update dependency html-webpack-plugin to v5.6.2 (#1085)

yarn.lock
=> [v9.0] fix(deps): update dependency @elastic/eui to v97.2.0 (#1093)

yarn.lock
=> [v8.x] fix(deps): update dependency @elastic/eui to v97.2.0 (#1093)

yarn.lock
=> [v8.15] fix(deps): update dependency @elastic/eui to v97.2.0 (#1093)

yarn.lock
=> [v8.16] fix(deps): update dependency @elastic/eui to v97.2.0 (#1093)

yarn.lock
=> [v8.17] fix(deps): update dependency @elastic/eui to v97.2.0 (#1093)

package.json, yarn.lock
=> [v9.0] chore(deps): update dependency eslint-plugin-react to v7.37.2 (#1107)

package.json, yarn.lock
=> [v9.0] chore(deps): update dependency html-webpack-plugin to v5.6.3 (#1108)

package.json, yarn.lock
=> [v8.x] chore(deps): update dependency html-webpack-plugin to v5.6.3 (#1108)

package.json, yarn.lock
=> [v8.15] chore(deps): update dependency eslint-plugin-react to v7.37.2 (#1107)

package.json, yarn.lock
=> [v8.15] chore(deps): update dependency html-webpack-plugin to v5.6.3 (#1108)

package.json, yarn.lock
=> [v8.16] chore(deps): update dependency eslint-plugin-react to v7.37.2 (#1107)

package.json, yarn.lock
=> [v8.16] chore(deps): update dependency html-webpack-plugin to v5.6.3 (#1108)

package.json, yarn.lock
=> [v7.17] chore(deps): update dependency eslint-plugin-react to v7.37.2 (#1107)

package.json, yarn.lock
=> [v7.17] chore(deps): update dependency html-webpack-plugin to v5.6.3 (#1108)

package.json, yarn.lock
=> [v8.17] chore(deps): update dependency eslint-plugin-react to v7.37.2 (#1107)

package.json, yarn.lock
=> [v8.17] chore(deps): update dependency html-webpack-plugin to v5.6.3 (#1108)

.backportrc.json
=> [v9.0] [skip-ci] update backport config for CI (#1127)

.backportrc.json
=> [v8.x] [skip-ci] update backport config for CI (#1127)

.backportrc.json
=> [v8.17] [skip-ci] update backport config for CI (#1127)

.backportrc.json
=> [v8.16] [skip-ci] update backport config for CI (#1127)

.backportrc.json
=> [v8.15] [skip-ci] update backport config for CI (#1127)

.backportrc.json
=> [v7.17] [skip-ci] update backport config for CI (#1127)

.backportrc.json
=> [v9.0] [skip-ci] fix repoName (#1134)

.backportrc.json
=> [v8.x] [skip-ci] fix repoName (#1134)

.backportrc.json
=> [v8.15] [skip-ci] fix repoName (#1134)

.backportrc.json
=> [v8.16] [skip-ci] fix repoName (#1134)

.backportrc.json
=> [v8.17] [skip-ci] fix repoName (#1134)

.backportrc.json
=> [v7.17] [skip-ci] fix repoName (#1134)

.backportrc.json
- [[skip-ci] Add label mapping to the backport configuration (#1141)](https://github.com/elastic/ems-landing-page/pull/1141)
- [[skip-ci] fix label mapping (#1142)](https://github.com/elastic/ems-landing-page/pull/1142)
=> [v8.x] [skip-ci] Add label mapping to the backport configuration (#1141) | [skip-ci] fix label mapping (#1142)

.backportrc.json
- [[skip-ci] Add label mapping to the backport configuration (#1141)](https://github.com/elastic/ems-landing-page/pull/1141)
- [[skip-ci] fix label mapping (#1142)](https://github.com/elastic/ems-landing-page/pull/1142)
=> [v8.15] [skip-ci] Add label mapping to the backport configuration (#1141) | [skip-ci] fix label mapping (#1142)

.backportrc.json
- [[skip-ci] Add label mapping to the backport configuration (#1141)](https://github.com/elastic/ems-landing-page/pull/1141)
- [[skip-ci] fix label mapping (#1142)](https://github.com/elastic/ems-landing-page/pull/1142)
=> [v8.16] [skip-ci] Add label mapping to the backport configuration (#1141) | [skip-ci] fix label mapping (#1142)

.backportrc.json
- [[skip-ci] Add label mapping to the backport configuration (#1141)](https://github.com/elastic/ems-landing-page/pull/1141)
- [[skip-ci] fix label mapping (#1142)](https://github.com/elastic/ems-landing-page/pull/1142)
=> [v7.17] [skip-ci] Add label mapping to the backport configuration (#1141) | [skip-ci] fix label mapping (#1142)

.github/workflows/sync_8.17.yml, .github/workflows/sync_9.0.yml
Adds two new github actions that will open PRs to keep:
* `v9.0` in sync with `master`
* `v8.17` in sync with `v8.x`
This will require an additional step when releasing new minors that will need to be documented later when the procedure is clear.
=> [skip-ci] New github actions to sync master and 8.x with v9.0 and v8.17

.github/workflows/backport.yml
- [[skip-ci] Ignore backport action for sync PRs #2 (#1221)](https://github.com/elastic/ems-landing-page/pull/1221)
=> [v8.x] [skip-ci] Ignore backport action for sync PRs #2 (#1221)

.github/workflows/backport.yml
- [[skip-ci] Ignore backport action for sync PRs #2 (#1221)](https://github.com/elastic/ems-landing-page/pull/1221)
=> [v8.16] [skip-ci] Ignore backport action for sync PRs #2 (#1221)

.github/workflows/backport.yml
- [[skip-ci] Ignore backport action for sync PRs #2 (#1221)](https://github.com/elastic/ems-landing-page/pull/1221)
=> [v8.15] [skip-ci] Ignore backport action for sync PRs #2 (#1221)

.github/workflows/backport.yml
- [[skip-ci] Ignore backport action for sync PRs #2 (#1221)](https://github.com/elastic/ems-landing-page/pull/1221)
=> [v7.17] [skip-ci] Ignore backport action for sync PRs #2 (#1221)

.backportrc.json, package.json, public/config.json, renovate.json
Bumps the master branch to 8.18 following the [New release docs](https://github.com/elastic/ems-landing-page/blob/4ac92161e4bc8e1eb82a0d98ea14ccf047ad21e2/CONTRIBUTING.md#new-releases)
- Updates the package.json to 8.18.0
- Updates the EMS version in the config file to 8.18
- Adds the 8.18 branch to the backport
- Updates renovate.json
>[!Important]
> In preparation of the new `v9.x` series. This PR is against the `v8.x` branch
>[!Important]
> After this PR is merged a sibling `v8.18` branch synchronized with `v8.x` will be created to deploy a new version in the `v8.18` route in our GCP buckets.
A follow up PR will be required to update the Github Action that synchronizes `v8.x` with the new branch.
=> Bumps to 8.18

.buildkite/scripts/build.sh, package.json, public/js/components/app.js, public/js/components/theme.js, public/main.css, webpack.common.js, yarn.lock
Fixes #1257 
* Switches to the EUI version that includes support for Borealis theme. This theme is only enabled based on a environment variable that for our CI will only work on the `v9.0` branch.
* Follows the user preference to enable the EUI dark mode, also switching automatically to the EMS `dark_matter` style accordingly.
<details>
<summary>Screenshots</summary>
</details>
> [!note]
> **How to test:**
>
> Just start the dev server with `EUI_THEME=borealis yarn dev`
>
> or visit https://storage.googleapis.com/jsanz-bucket/tmp/ems-landing-page/index.html
=> [Borealis] Enable Borealis theme and dark mode

.buildkite/scripts/build.sh
Small fix to get the `EUI_THEME` correctly set up for production deployments on the `v9.0` branch.
=> [ci] Get Borealis also for tag builds

renovate.json
This will backport the following commits from `master` to `v8.18`:
- [chore(config): migrate config renovate.json (#1563)](https://github.com/elastic/ems-landing-page/pull/1563)
=> [v8.18] chore(config): migrate config renovate.json (#1563)

renovate.json
- [chore(config): migrate config renovate.json (#1563)](https://github.com/elastic/ems-landing-page/pull/1563)
=> [v8.17] chore(config): migrate config renovate.json (#1563)

renovate.json
- [chore(config): migrate config renovate.json (#1563)](https://github.com/elastic/ems-landing-page/pull/1563)
=> [v8.16] chore(config): migrate config renovate.json (#1563)

.github/workflows/sync_8.18.yml, .github/workflows/sync_9.0.yml
This will backport the following commits from `master` to `v8.18`:
- [chore(deps): update actions/setup-node digest to 49933ea (#1884)](https://github.com/elastic/ems-landing-page/pull/1884)
=> [v8.18] chore(deps): update actions/setup-node digest to 49933ea (#1884)

.github/workflows/sync_8.18.yml, .github/workflows/sync_9.0.yml
- [chore(deps): update actions/setup-node digest to 49933ea (#1884)](https://github.com/elastic/ems-landing-page/pull/1884)
=> [v8.16] chore(deps): update actions/setup-node digest to 49933ea (#1884)

.github/workflows/sync_8.18.yml, .github/workflows/sync_9.0.yml
- [chore(deps): update actions/setup-node digest to 49933ea (#1884)](https://github.com/elastic/ems-landing-page/pull/1884)
=> [v7.17] chore(deps): update actions/setup-node digest to 49933ea (#1884)

.github/workflows/sync_9.0.yml
=> [v9.0] chore(deps): update actions/checkout digest to 08eba0b (#2297)

.github/workflows/sync_9.yml
This will backport the following commits from `master` to `v8.19`:
=> [v8.19] chore(deps): update actions/checkout digest to 08eba0b (#2297)

.github/workflows/sync_9.0.yml
This will backport the following commits from `master` to `v8.18`:
=> [v8.18] chore(deps): update actions/checkout digest to 08eba0b (#2297)

.github/workflows/sync_9.0.yml
=> [v7.17] chore(deps): update actions/checkout digest to 08eba0b (#2297)

package.json, yarn.lock
This will backport the following commits from `master` to `v8.19`:
- [fix(deps): update elastic eui (#2298)](https://github.com/elastic/ems-landing-page/pull/2298)
=> [v8.19] fix(deps): update elastic eui (#2298)

.github/workflows/sync_9.yml
This will backport the following commits from `master` to `v9.1`:
=> [v9.1] chore(deps): update actions/checkout digest to 08eba0b (#2297)

.github/workflows/sync_9.yml
This will backport the following commits from `master` to `v9.1`:
- [chore(deps): update actions/checkout action to v5 (#2320)](https://github.com/elastic/ems-landing-page/pull/2320)
=> [v9.1] chore(deps): update actions/checkout action to v5 (#2320)

.github/workflows/sync_9.0.yml
This will backport the following commits from `master` to `v8.18`:
- [chore(deps): update actions/checkout action to v5 (#2320)](https://github.com/elastic/ems-landing-page/pull/2320)
=> [v8.18] chore(deps): update actions/checkout action to v5 (#2320)

.github/workflows/sync_9.0.yml
- [chore(deps): update actions/checkout action to v5 (#2320)](https://github.com/elastic/ems-landing-page/pull/2320)
=> [v7.17] chore(deps): update actions/checkout action to v5 (#2320)
