- README.md
- package.json
- public/js/components/feature_table.js
- yarn.lock
Bump EUI and React to latest version and fix associated breaking changes.
> bump eui/react + address breaking changes

- README.md
- package.json
- public/js/components/app.js
- public/js/components/feature_table.js
- public/js/components/table_of_contents.js
- public/style/main.css
- yarn.lock
This includes
- version bump of EUI/React + redress breaking changes
- addition of EMS logo
- minor styling adjustments
> Add EMS logo

- public/js/config.json
- public/js/main.js
make default version configurable
> make manifest selection configurable

- public/js/config.json
Uses staging as the default config on the master branch.
> use staging as default

- Gruntfile.js
- package.json
Zipping things per branch makes things harder, so I handled it in the Jenkins job. Removing from the build.
> remove release compression

- public/js/components/feature_table.js
replaces https://github.com/elastic/ems-landing-page/pull/20
> Use row-click to highlight country

- public/style/main.css
Closes https://github.com/elastic/ems-landing-page/issues/22.
> improve balloon button

- README.md
- build.sh
- deployProduction.sh
- deployStaging.sh
- package.json
Note that this will break Jenkins build job until they are updated
(separate patch, but this should be merged first)
The jjb update is in https://github.com/elastic/infra/pull/5889
> build and deployment scripts for Jenkins automation

- public/js/components/table_of_contents.js
Closes https://github.com/elastic/ems-landing-page/issues/34.
> Do not assign clickhandler to header

- public/js/components/app.js
- public/js/components/map.js
Closes https://github.com/elastic/ems-landing-page/issues/33.
> Show webgl warning

- .backportrc.json
- README.md
- package.json
- public/js/components/app.js
- public/js/components/feature_table.js
- public/js/components/map.js
- public/js/components/table_of_contents.js
- yarn.lock
This merged master in v2, backporting the latest changes
> Backport latest changes

- public/config.json
- Update staging URL for EMS  (#47)
> [v2] Update staging URL for EMS (#47)

- deployProduction.sh
Apparently Google hasn't released their fix just yet:
https://github.com/GoogleCloudPlatform/gsutil/issues/575
> Temp remove --user when depl in docker

- package.json
- public/js/components/map.js
- yarn.lock
Fixes #13.
This adds map attribution to the corner of the map.
> [v2] Add basemap attribution

- package.json
- public/main.js
- yarn.lock
- Polyfill fetch for IE11  (#53)
> [v6.6] Polyfill fetch for IE11 (#53)

- package.json
- public/main.js
- yarn.lock
- Polyfill fetch for IE11  (#53)
> [v2] Polyfill fetch for IE11 (#53)

- public/js/components/table_of_contents.js
This allows a user to hover over truncated layers in the side nav to see the full text.
> [v2] Add title property to sidenavs

- public/js/components/table_of_contents.js
Cherry-picks the following commit to v6.6:
* Add title property to sidenavs  #70
> [v6.6] Add title property to sidenavs

- public/main.js
Needs to be merged into 6.7, 7.0 and master.
> Simplify deployment input check

- public/main.js
This merges in the safer deployment check from v6.6 and fixes merge conflicts.
> Merge v6.6 into v6.7

- .ci/jobs/elastic+ems-landing-page+v7.2+stage.yml
Add the v7.2 branch to ci so we can publish this release to production.
> Add v7.2 branch to ci

- .ci/jobs/defaults.yml
- .ci/jobs/elastic+ems-landing-page+deploy.yml
- .ci/jobs/elastic+ems-landing-page+master+stage.yml
- .ci/jobs/elastic+ems-landing-page+v2+stage.yml
- .ci/jobs/elastic+ems-landing-page+v6.6+stage.yml
- .ci/jobs/elastic+ems-landing-page+v6.7+stage.yml
- .ci/jobs/elastic+ems-landing-page+v7.0+stage.yml
- .ci/jobs/elastic+ems-landing-page+v7.2+stage.yml
- deployProduction.sh
- deployStaging.sh
Closes https://github.com/elastic/ems-landing-page/issues/104
> Use master branch for development and backport changes to branches

- public/js/ems_client.js
- public/js/tms_service.js
> Fix missing tilemap when locale is set

- public/js/ems_client.js
- public/js/tms_service.js
- Fix missing tilemap when locale is set (#108)
> [v7.2] Fix missing tilemap when locale is set (#108)

- package.json
- public/index.html
- public/js/components/app.js
- yarn.lock
> Optimize https redirect

- public/main.js
- Enable higher zoom levels (#123)
> [v6.6] Enable higher zoom levels (#123)

- public/config.json
- public/main.js
- Enable higher zoom levels (#123)
> [v6.7] Enable higher zoom levels (#123)

- public/config.json
- public/main.js
- Enable higher zoom levels (#123)
> [v7.0] Enable higher zoom levels (#123)

- public/config.json
- public/main.js
- Enable higher zoom levels (#123)
> [v7.2] Enable higher zoom levels (#123)

- package.json
- public/index.html
- public/js/components/app.js
- yarn.lock
> [v2] Optimize https redirect (#124)

- package.json
- public/index.html
- public/js/components/app.js
- yarn.lock
> [v6.6] Optimize https redirect (#124)

- package.json
- public/index.html
- public/js/components/app.js
- yarn.lock
> [v6.7] Optimize https redirect (#124)

- package.json
- public/index.html
- public/js/components/app.js
- yarn.lock
> [v7.0] Optimize https redirect (#124)

- package.json
- public/index.html
- public/js/components/app.js
- yarn.lock
> [v7.2] Optimize https redirect (#124)

- package.json
- yarn.lock
- Fix IE11 compatibility (#148)
> [v7.4] Fix IE11 compatibility (#148)

- package.json
- yarn.lock
Fixes #150
Needs backport to 7.4
> Bump @elastic/ems-client to 7.2.2

- .backportrc.json
- .ci/jobs/defaults.yml
- .ci/jobs/elastic+ems-landing-page+v7.6.yml
- Add v7.6 branch to ci (#156)
- Default to v7.6 (#159)
> [v7.6] Add v7.6 branch to ci (#156) | Default to v7.6 (#159)

- .ci/jobs/elastic+ems-landing-page+v7.7.yml
- package.json
- public/config.json
- public/main.js
- yarn.lock
> [v7.7] Update to EMS v7.7 (#170)

- yarn.lock
> [v2] Update dependencies (#169)

- yarn.lock
> [v6.6] Update dependencies (#169)

- yarn.lock
> [v6.7] Update dependencies (#169)

- yarn.lock
> [v7.0] Update dependencies (#169)

- yarn.lock
> [v7.2] Update dependencies (#169)

- yarn.lock
> [v7.4] Update dependencies (#169)

- yarn.lock
> [v7.6] Update dependencies (#169)

- yarn.lock
> [v7.7] Update dependencies (#169)

- .ci/jobs/defaults.yml
- .ci/jobs/elastic+ems-landing-page+deploy.yml
- .ci/jobs/elastic+ems-landing-page+master+stage.yml
- .ci/jobs/elastic+ems-landing-page+v2+stage.yml
- .ci/jobs/elastic+ems-landing-page+v6.6+stage.yml
- .ci/jobs/elastic+ems-landing-page+v6.7+stage.yml
- .ci/jobs/elastic+ems-landing-page+v7.0+stage.yml
- .ci/jobs/elastic+ems-landing-page+v7.2+stage.yml
- .ci/jobs/elastic+ems-landing-page+v7.4+stage.yml
- .ci/jobs/elastic+ems-landing-page+v7.6.yml
- .ci/jobs/elastic+ems-landing-page+v7.7.yml
Switch the role for deployment
> [bekitzur] use specific role for deployment

- package.json
- public/js/components/map.js
- public/main.js
- yarn.lock
Fixes #168 
~Relies on @elastic/ems-client@7.7.2 (https://github.com/elastic/ems-client/pull/21). CI failures are expected until this is released.~
> Allow relative API URLs in config

- public/main.js
- Fix parsing emsVersion from config (#182)
> [v7.7] Fix parsing emsVersion from config (#182)

- public/js/components/app.js
> [v2] Handle empty #file anchor in URL (#186)

- .ci/jobs/elastic+ems-landing-page+v7.8.yml
- CONTRIBUTING.md
- package.json
- public/config.json
- yarn.lock
Update CI and the config to publish v7.8 release of ems-landing-page﻿.
> Publish 7.8

- .backportrc.json
- CONTRIBUTING.md
- README.md
Updating and consolidating the release process docs into CONTRIBUTING.md
> Update release process docs

- .ci/jobs/defaults.yml
> [v7.8] Bump root to v7.8 (#217)

- .ci/jobs/elastic+ems-landing-page+v7.9.yml
- package.json
- public/config.json
- yarn.lock
Per the instructions in [CONTRIBUTING](https://github.com/elastic/ems-landing-page/blob/master/CONTRIBUTING.md#new-releases).
Fixes #206
> Update to EMS v7.9

- .ci/jobs/defaults.yml
> [v7.9] Update defaults.yml (#231)

- package.json
- public/js/components/app.js
- yarn.lock
Fixes #235 and #140 
This PR would add links to the EMS Terms of Service and this GitHub repo to https://maps.elastic.co. 
Additionally, the link for reporting data issues is changed to the ems-file-service repo.
cc @mbarretta @richardim
> Add external links

- package.json
- public/js/components/app.js
- public/js/components/layer_details.js
- yarn.lock
- Generate attribution-string safely (#228)
- Add external links (#236)
> [v7.8] Generate attribution-string safely (#228) | Add external links (#236)

- package.json
- public/js/components/app.js
- public/js/components/layer_details.js
- yarn.lock
- Generate attribution-string safely (#228)
- Add external links (#236)
> [v7.9] Generate attribution-string safely (#228) | Add external links (#236)

- .backportrc.json
- .ci/jobs/elastic+ems-landing-page+v7.10.yml
- CONTRIBUTING.md
- package.json
- public/config.json
- yarn.lock
Following the New Releases instructions in CONTRIBUTING.MD.
> Publish EMS v7.10

- webpack.common.js
> [v2] Build option to host under path other than root (#258)

- webpack.common.js
> [v2] Use default publicPath if ASSET_PATH is not specified (#259)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
- upgrade to EUI 30.4.0
- Fixed height for the TOC
- Icons in header links
Preview:
> Update to EUI 30.4.0

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v2] Update to EUI 30.4.0 (#286)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v6.7] Update to EUI 30.4.0 (#286)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v6.6] Update to EUI 30.4.0 (#286)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v7.0] Update to EUI 30.4.0 (#286)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v7.2] Update to EUI 30.4.0 (#286)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v7.4] Update to EUI 30.4.0 (#286)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v7.6] Update to EUI 30.4.0 (#286)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v7.7] Update to EUI 30.4.0 (#286)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v7.8] Update to EUI 30.4.0 (#286)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v7.9] Update to EUI 30.4.0 (#286)

- package.json
- public/js/components/app.js
- public/main.css
- yarn.lock
> [v7.10] Update to EUI 30.4.0 (#286)

- .backportrc.json
- .ci/jobs/elastic+ems-landing-page+v7.11.yml
- README.md
- package.json
- public/config.json
- yarn.lock
Part of elastic/ems-file-service#200
- Publish EMS v7.11
- upgrade dependencies with yarn upgrade
> Publish EMS v7.11

- package.json
- public/js/components/feature_table.js
- yarn.lock
- Download GeoJSON when available (#256)
> [v7.10] Download GeoJSON when available (#256)

- public/js/components/app.js
- public/js/components/layer_details.js
Backports the following commits to v7.11:
- Add details for currently selected tile layer (#305)
> [v7.11] Add details for currently selected tile layer (#305)

- .ci/jobs/defaults.yml
Following guidelines for release in [CONTRIBUTING.MD](https://github.com/elastic/ems-landing-page/blob/master/CONTRIBUTING.md)
> Update maps.elastic.co to 7.11

- .ci/jobs/defaults.yml
Backports the following commits to v7.11:
- Update defaults.yml (#308)
> [v7.11] Update defaults.yml (#308)

- .backportrc.json
- .ci/jobs/elastic+ems-landing-page+v7.12.yml
- package.json
- public/config.json
- yarn.lock
Follows [CONTRIBUTING.MD](https://github.com/elastic/ems-landing-page/blob/master/CONTRIBUTING.md) for a new EMS release
> Use EMS 7.12

- yarn.lock
Backports the following commits to v7.12:
> [v7.12] Update dependencies (#315)

- yarn.lock
Backports the following commits to v7.11:
> [v7.11] Update dependencies (#315)

- yarn.lock
> [v7.10] Update dependencies (#315)

- yarn.lock
> [v7.9] Update dependencies (#315)

- yarn.lock
> [v7.8] Update dependencies (#315)

- yarn.lock
> [v7.7] Update dependencies (#315)

- yarn.lock
> [v7.6] Update dependencies (#315)

- yarn.lock
> [v7.4] Update dependencies (#315)

- yarn.lock
> [v7.2] Update dependencies (#315)

- yarn.lock
> [v7.0] Update dependencies (#315)

- yarn.lock
> [v6.7] Update dependencies (#315)

- yarn.lock
> [v6.6] Update dependencies (#315)

- yarn.lock
> [v2] Update dependencies (#315)

- .backportrc.json
- .ci/jobs/elastic+ems-landing-page+v7.13.yml
- package.json
- public/config.json
- public/js/components/app.js
- yarn.lock
Backports the following commits to v7.13:
- Bump to EMS v7.13 (#329)
> [v7.13] Bump to EMS v7.13 (#329)

- .backportrc.json
- .ci/jobs/elastic+ems-landing-page+v7.14.yml
- package.json
- public/config.json
- yarn.lock
Following the guidelines in CONTRIBUTING.md for a new release.
> Bump to EMS v7.14

- .backportrc.json
- .ci/jobs/elastic+ems-landing-page+v8.0.yml
- package.json
- public/config.json
- yarn.lock
Preps landing page for EMS 8.0.
Should only be merged after https://github.com/elastic/ems-file-service/pull/229 & https://github.com/elastic/ems-client/pull/82
Expect tests to fail until those PRs are merged.
> Bump to EMS 8.0

- public/js/components/app.js
- public/js/components/table_of_contents.js
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
Backports the following commits to v7.15:
- Reduce output assets number (#377)
> [v7.15] Reduce output assets number (#377)

- public/js/components/app.js
- public/js/components/table_of_contents.js
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
Backports the following commits to v8.0:
- Reduce output assets number (#377)
> [v8.0] Reduce output assets number (#377)

- .backportrc.json
- .ci/jobs/elastic+ems-landing-page+v7.17.yml
* Remove branches that are not deployed anymore
* Add 7.17 to backport config
> Update backport config

- .ci/jobs/elastic+ems-landing-page+v8.1.yml
- public/config.json
The EMS version needs updating and the new 8.1 branch needs to be built.
> Publish 8.1 landing page

- .gitignore
- yarn.lock
This is an automatic backport of pull request #407 to v7.15.
> [v7.15] February updates (#407)

- .gitignore
- yarn.lock
This is an automatic backport of pull request #407 to v7.16.
> [v7.16] February updates (#407)

- .gitignore
- yarn.lock
This is an automatic backport of pull request #407 to v7.17.
> [v7.17] February updates (#407)

- .gitignore
- yarn.lock
This is an automatic backport of pull request #407 to v8.0.
> [v8.0] February updates (#407)

- .ci/jobs/elastic+ems-landing-page+v8.1.yml
- public/config.json
Backports the following commits to v8.1:
- Publish 8.1 landing page (#402)
> [v8.1] Publish 8.1 landing page (#402)

- .gitignore
- yarn.lock
This is an automatic backport of pull request #407 to v8.2.
> [v8.2] February updates (#407)

- .gitignore
- yarn.lock
This is an automatic backport of pull request #407 to v8.1.
> [v8.1] February updates (#407)

- .backportrc.json
- .ci/jobs/elastic+ems-landing-page+v8.3.yml
- package.json
Branch `8.3` will be cut from this PR
> Bump to 8.3.0

- .ci/jobs/defaults.yml
- package.json
- public/config.json
- yarn.lock
Updates EMS Client and points to manifests for 8.2 version.
> Update to stack and client 8.2

- .ci/jobs/defaults.yml
- package.json
- public/config.json
- yarn.lock
This is an automatic backport of pull request #420 to v8.2.
> [v8.2] Update to stack and client 8.2 (#420)

- package.json
- yarn.lock
This is an automatic backport of pull request #418 to v8.1.
> [v8.1] March Updates (#418)

- package.json
- yarn.lock
This is an automatic backport of pull request #418 to v8.2.
> [v8.2] March Updates (#418)

- public/js/components/layer_details.js
This is an automatic backport of pull request #431 to v7.17.
> [v7.17] Add a badge with default format for FileLayers (#431)

- package.json
- public/js/components/app.js
- public/js/components/customize_tms.js
- public/js/components/layer_details.js
- public/js/components/map.js
- public/js/components/table_of_contents.js
- public/main.css
- yarn.lock
This is a new PR coming from #429 only adding the custom language part:
* Removes the initial selection of a file layer to just display the basemap
* Label layers on the map style are rendered on top of selected file layer
* Adds a new form control to allow changing the language of the basemap labels
> [Spacetime] Custom languages

- package.json
- public/js/components/app.js
- public/js/components/customize_tms.js
- public/js/components/layer_details.js
- public/js/components/map.js
- public/js/components/table_of_contents.js
- public/main.css
- yarn.lock
Backports the following commits to v8.4:
- [Spacetime] Custom languages (#434)
> [v8.4] [Spacetime] Custom languages (#434)

- public/js/components/app.js
- public/js/components/customize_tms.js
- public/js/components/layer_details.js
- public/js/components/map.js
This will backport the following commits from `master` to `v8.4`:
- [[Spacetime] Custom basemap colors (#435)](https://github.com/elastic/ems-landing-page/pull/435)
> [v8.4] [Spacetime] Custom basemap colors (#435)

- package.json
- yarn.lock
> Upgrade chroma-js@2.4.2

- .backportrc.json
- .ci/jobs/elastic+ems-landing-page+v8.9.yml
- package.json
* Bumps `package.json` to 8.9.0
* Adds the `v8.9` branch to the backport config (the branch will be created after this PR is merged)
* Creates the Jenkins job for 8.9 (a new commit will be added to #552)
> Bump to 8.9

- .buildkite/pipeline.yml
Fixing an error in #552 
The current regex was capturing also backport branches.
> Fix the branch check to stage and deploy

- .buildkite/hooks/pre-command
- .buildkite/pipeline.yml
- .buildkite/scripts/archive.sh
- .buildkite/scripts/build.sh
- .buildkite/scripts/upload.sh
- catalog-info.yaml
- deployProduction.sh
- deployStaging.sh
- [Buildkite deploy (#552)](https://github.com/elastic/ems-landing-page/pull/552)
- [Fix the branch check to stage and deploy (#575)](https://github.com/elastic/ems-landing-page/pull/575)
> [v8.9] Buildkite deploy (#552) | Fix the branch check to stage and deploy (#575)

- .buildkite/hooks/pre-command
- .buildkite/pipeline.yml
- .buildkite/scripts/archive.sh
- .buildkite/scripts/build.sh
- .buildkite/scripts/upload.sh
- catalog-info.yaml
- deployProduction.sh
- deployStaging.sh
- [Buildkite deploy (#552)](https://github.com/elastic/ems-landing-page/pull/552)
- [Fix the branch check to stage and deploy (#575)](https://github.com/elastic/ems-landing-page/pull/575)
> [v8.8] Buildkite deploy (#552) | Fix the branch check to stage and deploy (#575)

- .buildkite/hooks/pre-command
- .buildkite/pipeline.yml
- .buildkite/scripts/archive.sh
- .buildkite/scripts/build.sh
- .buildkite/scripts/upload.sh
- catalog-info.yaml
- deployProduction.sh
- deployStaging.sh
- [Buildkite deploy (#552)](https://github.com/elastic/ems-landing-page/pull/552)
- [Fix the branch check to stage and deploy (#575)](https://github.com/elastic/ems-landing-page/pull/575)
> [v8.7] Buildkite deploy (#552) | Fix the branch check to stage and deploy (#575)

- .buildkite/hooks/pre-command
- .buildkite/pipeline.yml
- .buildkite/scripts/archive.sh
- .buildkite/scripts/build.sh
- .buildkite/scripts/upload.sh
- catalog-info.yaml
- deployProduction.sh
- deployStaging.sh
- [Buildkite deploy (#552)](https://github.com/elastic/ems-landing-page/pull/552)
- [Fix the branch check to stage and deploy (#575)](https://github.com/elastic/ems-landing-page/pull/575)
> [v7.17] Buildkite deploy (#552) | Fix the branch check to stage and deploy (#575)

- .buildkite/scripts/archive.sh
Avoids large logs in the CI output.
> Reduces verbosity of archive download and compression commands

- public/config.json
> Fix EMS version in config.json (8.9)

- .backportrc.json
- package.json
* Bumps `package.json` to 8.10.0
* Adds the `v8.10` branch to the backport config (the branch will be created after this PR is merged)
> Bump to 8.10

- package.json
- yarn.lock
Runing `yarn upgrade-interactive` to upgrade semver, emotion/ccss, and many other dependencies
> Upgrades Y23W28

- .buildkite/pipeline.yml
Fixes pipeline steps not picking commits to the SemVer branches for staging
> Fix buildkite pipeline

- .buildkite/pipeline.yml
Makes the condition to trigger deploys more relaxed to accept branche names (tags for buildkite?).
> Relax condition for deploy

- package.json
- yarn.lock
Related to #664 but applied to `master` and the other active release branches
> Upgrade whatwg-fetch from 3.6.2 to 3.6.16

- package.json
- public/js/components/app.js
- public/main.js
- yarn.lock
Fixes #603
Fixes #203
* Upgraded to `@elastic/eui@89.1.0` without any further code change
* Added a console message on load to show the EMS version
* Added a tooltip to the title logo to show the EMS version (with a long delay to not annoy casual users)
> Upgrade EUI, show version on tooltip

- .buildkite/scripts/build.sh
- .buildkite/scripts/serverless.mjs
- package.json
- yarn.lock
- [Update emsVersion in the config.json file when running on master branch (#679)](https://github.com/elastic/ems-landing-page/pull/679)
> [v8.12] Update emsVersion in the config.json file when running on master branch (#679)

- .buildkite/scripts/build.sh
- .buildkite/scripts/serverless.mjs
- package.json
- yarn.lock
- [Update emsVersion in the config.json file when running on master branch (#679)](https://github.com/elastic/ems-landing-page/pull/679)
> [v7.17] Update emsVersion in the config.json file when running on master branch (#679)

- public/main.js
- [refactor: 💡 Use createRoot (React 18) (#746)](https://github.com/elastic/ems-landing-page/pull/746)
> [v8.13] refactor: 💡 Use createRoot (React 18) (#746)

- package.json
- webpack.common.js
- yarn.lock
Minor changes to the webpack config and two new packages were required for this upgrade.
> Upgrade @elastic/ems-client@8.5.3

- package.json
- webpack.common.js
- yarn.lock
Related with #763, applied to the `v7.17` branch
> [7.17] Upgrade @elastic/ems-client@7.17.3

- .backportrc.json
- .github/workflows/add_backport_label.yml
- .github/workflows/backport.yml
- .github/workflows/sync_8.18.yml
- renovate.json
> [skip-ci] Update settings after 8.18 bump

- .buildkite/pipeline.yml
- .nvmrc
- package.json
Upgrades the CI pipeline and references to Node 22.
> Update to Node 22

- package.json
- yarn.lock
This will backport the following commits from `master` to `v9.1`:
- [fix(deps): update elastic eui (#2298)](https://github.com/elastic/ems-landing-page/pull/2298)
> [v9.1] fix(deps): update elastic eui (#2298)
